### ISSUE TITLE
TaskCanceledException while building dotnet/llilc

### ISSUE THREAD

**Issue by krk** [Microsoft/msbuild#121]
MSBuild is crashing while building and running llilc tests at https://github.com/dotnet/llilc

```
  Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: MSBuild.exe
  Problem Signature 02: 12.0.31101.0
  Problem Signature 03: 545443d5
  Problem Signature 04: mscorlib
  Problem Signature 05: 4.6.57.0
  Problem Signature 06: 551b8848
  Problem Signature 07: 5afe
  Problem Signature 08: 26
  Problem Signature 09: FOPL4MYEJCHQ4QUDLY5M1JG1EE1KJYWU
  OS Version:   6.3.9600.2.0.0.256.48
  Locale ID:    2057
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: a10f
  Additional Information 4: a10ff7d2bb2516fdc753f9c34fc3b069

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-GB\erofflps.txt

```

**Comment by sarajoiner** [comment]
When MSBuild crashes, it usually dumps a text file called MSBuild_<guid>.failures.txt to the TEMP directory with the stack of the unhandled exception that caused the crash.  When trying to root-cause a crash, looking at either that or a dump of the crashing process is almost always more helpful than the above crash information.

**Comment by krk** [comment]
Thank you for the explanation, here are the contents of the failure file in TEMP directory.

```
UNHANDLED EXCEPTIONS FROM PROCESS 9884:
=====================
28/06/2015 20:14:17
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Split(String[] separator, Int32 count, StringSplitOptions options)
   at Microsoft.Build.Shared.EventArgsFormatting.FormatEventMessage(String category, String subcategory, String message, String code, String file, String projectFile, Int32 lineNumber, Int32 endLineNumber, Int32 columnNumber, Int32 endColumnNumber, Int32 threadId)
   at Microsoft.Build.Shared.EventArgsFormatting.FormatEventMessage(BuildErrorEventArgs e, Boolean removeCarriageReturn, Boolean showProjectFile)
   at Microsoft.Build.BackEnd.Logging.ParallelConsoleLogger.ErrorHandler(Object sender, BuildErrorEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent, Int32 sinkId)
   at Microsoft.Build.BackEnd.Logging.EventRedirectorToSink.Microsoft.Build.Framework.IEventRedirector.ForwardEvent(BuildEventArgs buildEvent)
   at Microsoft.Build.Logging.ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs e)
   at Microsoft.Build.Logging.ConfigurableForwardingLogger.ErrorHandler(Object sender, BuildErrorEventArgs e)
   at Microsoft.Build.Framework.BuildErrorEventHandler.Invoke(Object sender, BuildErrorEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)
===================
28/06/2015 20:16:49
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
===================
```

**Comment by AndyGerlicher** [comment]
Is there a custom task running at the time? Any idea what it's trying to log? And if lowering the verbosity helps the issue? We would also need to get some repro steps to try to help.

**Comment by jeffkl** [comment]
Please re-open this if it still repros.  We've made some fixes in this area.
