### ISSUE TITLE
MSB1025: An internal failure occurred while running MSBuild on Nano Server

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/msbuild#1233]
Copied from https://github.com/dotnet/cli/issues/4469
## Steps to reproduce

Build the following Windows Container Dockerfile via `docker build -t preview3 .`

```
FROM microsoft/nanoserver:10.0.14393.321

# Install .NET Core SDK
ENV DOTNET_SDK_VERSION 1.0.0-preview3-003892
ENV DOTNET_SDK_DOWNLOAD_URL https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-dev-win-x64.$DOTNET_SDK_VERSION.zip

RUN powershell -NoProfile -Command \
        $ErrorActionPreference = 'Stop'; \
        Invoke-WebRequest %DOTNET_SDK_DOWNLOAD_URL% -OutFile dotnet.zip; \
        Expand-Archive dotnet.zip -DestinationPath '%ProgramFiles%\dotnet'; \
        Remove-Item -Force dotnet.zip

RUN setx /M PATH "%PATH%;%ProgramFiles%\dotnet"

# Trigger the population of the local package cache
ENV NUGET_XMLDOC_MODE skip
RUN mkdir warmup \
    && cd warmup \
    && dotnet new \
    && cd .. \
    && rmdir /q/s warmup
```
## Expected  behavior

Dockerfile builds without issues.
## Actual behavior

Dockfile fails to build

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.EntryPointNotFoundException: Unable to find an entry point named 'RtlMoveMemory' in DLL 'kernel32.dll'.
   at Microsoft.Build.Internal.CommunicationsUtilities.CopyMemory(Char* destination, Char* source, UInt32 length)
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentCharArray()
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection()
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'RtlMoveMemory' in DLL 'kernel32.dll'.
   at Microsoft.Build.Internal.CommunicationsUtilities.CopyMemory(Char* destination, Char* source, UInt32 length)
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentCharArray()
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection()
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
Failed to create prime the NuGet cache. restore3 failed with: 255
```
## Environment data

I am using a WS16 environment with the latest updates.

This issue was caught by the dotnet-docker-nightly repo's CI which automatically picks up the latest CLI builds
[PR to uptake 003892](https://github.com/dotnet/dotnet-docker-nightly/pull/78)
[CI failure](https://ci.dot.net/job/dotnet_dotnet-docker-nightly/job/master/job/NanoServer_prtest/10/console)

**Comment by rainersigwald** [comment]
@MichaelSimons so this is failing only inside the container, or everywhere on Server 2016?

**Comment by MichaelSimons** [comment]
@rainersigwald I suspect this is specific to Nano Server but I haven't setup a standalone nano environment to verify.

**Comment by MichaelSimons** [comment]
@rainersigwald - any update on this?

**Comment by rainersigwald** [comment]
`RtlMoveMemory` isn't listed as an available [Nano Server API](https://msdn.microsoft.com/en-us/library/mt588480(v=vs.85).aspx), so that is likely the problem. We should be able to fall back to the "unoptimized" path for all .NET Core builds.

**Comment by rainersigwald** [comment]
Taking a quick look at other uses of [APIs exposed by `kernel32.dll`](https://github.com/Microsoft/msbuild/search?utf8=%E2%9C%93&q=kernel32.dll) makes me suspect this is just the first problem we'll see on Nano Server.

**Comment by rainersigwald** [comment]
Well, one layer of the onion is removed--it fails differently now:

```
C:\testsapp>dotnet build
Microsoft (R) Build Engine version 15.1.451.4340
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly.\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018: System.DllNotFoundException: Unable to load DLL 'mscoree.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.NativeMethods.GetFileVersion(String szFullPath, StringBuilder szBuffer, Int32 cchBuffer, UInt32& dwLength)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.AssemblyInformation.GetRuntimeVersion(String path)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.AssemblyInformation.IsWinMDFile(String fullPath, GetAssemblyRuntimeVersion getAssemblyRuntimeVersion, FileExists fileExists, String& imageRuntimeVersion, Boolean& isManagedWinmd)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.Reference.set_FullPath(String value)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.ReferenceTable.ResolveReference(AssemblyNameExtension assemblyName, String rawFileNameCandidate, Reference reference)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryItems(ITaskItem[] referenceAssemblyFiles, ITaskItem[] referenceAssemblyNames, ArrayList exceptions)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.ReferenceTable.ComputeClosure(DependentAssembly[] remappedAssembliesValue, ITaskItem[] referenceAssemblyFiles, ITaskItem[] referenceAssemblyNames, ArrayList exceptions)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [C:\testsapp\testsapp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004176\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [C:\testsapp\testsapp.csproj]
```

**Comment by jeffkl** [comment]
[GetFileVersion](https://github.com/Microsoft/msbuild/blob/07b0b369171f8cf93930945dec77dc4f32e9df28/src/XMakeTasks/NativeMethods.cs#L1316) calls into `mscoree.dll` ☹️

**Comment by rainersigwald** [comment]
We already have an alternate implementation for that codepath, though!

https://github.com/rainersigwald/msbuild/blob/6c723e9e133e5cc77ea0255bb51b577e3b178e97/src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs#L489

Just need to change the condition away from `IsWindows` (I suspect this will be a theme in Nano Server support).
