### ISSUE TITLE
OOM in CLI x86 Windows build when /v:diag

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/msbuild#1491]
I don't have a self-contained repro for this, but am happy to work with anyone  that investigates this to get to the bottom of the issue.

We recently turned on verbose console logging in CLI. This had the desired effect on all build flavors except x86 Windows where we started seeing OutOfMemory exceptions. Turning the verbosity back down to `normal` eliminated the exception. 

The build step in question is quite contained. There are 37 lines of verbose output at the time that the OOM occurs. Here is the relevant output:
```
2016-12-16T12:11:06.4902191Z                    Set Property: SdkInstallerNupkgFile=D:\DOTNET-CLI-W004\_work\4\s\/artifacts/win10-x86/packages/VS.Redist.Common.Net.Core.SDK.x86.1.0.0-preview5-004262.nupkg
2016-12-16T12:13:15.3666181Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2016-12-16T12:13:15.3666181Z System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
2016-12-16T12:13:15.3666181Z    at Microsoft.Build.Execution.BuildManager.EndBuild()
2016-12-16T12:13:15.3666181Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
2016-12-16T12:13:15.3666181Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2016-12-16T12:13:15.3666181Z System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
2016-12-16T12:13:15.3666181Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
2016-12-16T12:13:15.3666181Z    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
2016-12-16T12:13:15.3666181Z Unhandled Exception: OutOfMemoryException.
```

@jeffkl

**Comment by danmosemsft** [comment]
@piotrpMSFT the best way to proceed with this would be to get a memory dump at the point of failure. Then it should be fairly straightforward to dump the heap to see what is using up the memory. Not necessarily easy to figure out the fix but presumably it's localized to logging.

**Comment by zhouwei25** [comment]
@TheRealPiotrP Have you fixed this problem? I have this problem,too. It bothers me for a long time
