### ISSUE TITLE
**.* exclude pattern throws exception

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1523]
The following project
```xml
<Project>
    <ItemGroup>
       <i Include="**\*" Exclude="**.*"/>
    </ItemGroup>

    <Target Name="Build">
        <Message Text="[@(i)]" Importance="high"/>
    </Target>
</Project>
```

Throws an exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.FileUtilities.ToSlash(String s) in d:\projects\msbuild_2\src\Shared\FileUtilities.cs:line 1016
   at Microsoft.Build.Shared.FileUtilities.NormalizeForPathComparison(String s) in d:\projects\msbuild_2\src\Shared\FileUtilities.cs:line 1019
   at Microsoft.Build.Shared.FileMatcher.GetFiles(String projectDirectoryUnescaped, String filespecUnescaped, IEnumerable`1 excludeSpecsUnescaped, GetFileSystemEntries getFileS
ystemEntries, DirectoryExists directoryExists) in d:\projects\msbuild_2\src\Shared\FileMatcher.cs:line 1584
   at Microsoft.Build.Shared.FileMatcher.GetFiles(String projectDirectoryUnescaped, String filespecUnescaped, IEnumerable`1 excludeSpecsUnescaped) in d:\projects\msbuild_2\src\
Shared\FileMatcher.cs:line 1351
   at Microsoft.Build.Internal.EngineFileUtilities.GetFileList(String directoryEscaped, String filespecEscaped, Boolean returnEscaped, IEnumerable`1 excludeSpecsEscaped) in d:\
projects\msbuild_2\src\XMakeBuildEngine\Utilities\EngineFileUtilities.cs:line 131
   at Microsoft.Build.Internal.EngineFileUtilities.GetFileListEscaped(String directoryEscaped, String filespecEscaped, IEnumerable`1 excludeSpecsEscaped) in d:\projects\msbuild
_2\src\XMakeBuildEngine\Utilities\EngineFileUtilities.cs:line 60
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.IncludeOperation.SelectItems(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in d:\projects\msbuild_2\src\XMakeBuild
Engine\Evaluation\LazyItemEvaluator.IncludeOperation.cs:line 103
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemOperation.Apply(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in d:\projects\msbuild_2\src\XMakeBuildEngin
e\Evaluation\LazyItemEvaluator.LazyItemOperation.cs:line 47
```

MSBuild 14 ignores the `**.*` exclude (actually, it treats it as a literal string, and on windows no files can match it, and therefore it behaves like it's ignored)

**Comment by cdmihai** [comment]
Up until now, msbuild considered such patterns as illegal: https://github.com/Microsoft/msbuild/blob/xplat/src/Shared/UnitTests/FileMatcher_Tests.cs#L558-L562

If they are encountered in an include, the pattern is returned as is. If they are encountered in an exclude, they get ignored.

We could change the behaviour such that `**.cs` is interpreted as `*.cs`. Though that would be a breaking change for users who relied on these illegal patterns as being treated as literals.
