### ISSUE TITLE
VS churns up memory and app hangs during build with multiple targets

### ISSUE THREAD

**Issue by ChrisMcKee** [Microsoft/msbuild#1797]
![image](https://cloud.githubusercontent.com/assets/83597/23612755/8717f890-0274-11e7-9f3f-a0ce08e5e6e5.png)

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>BCrypt.Net, C# implementation of BCrypt, OpenBSD-style Blowfish password hashing</Description>
        <AssemblyTitle>BCrypt.Net-Next</AssemblyTitle>
        <VersionPrefix>2.0.2</VersionPrefix>
        <Authors>https://github.com/BcryptNet/bcrypt.net</Authors>
        <TargetFrameworks>net20;net35;net40;net45;net451;net452;net462;netstandard1.3;netstandard1.6;netcoreapp1.0</TargetFrameworks>
        <AssemblyName>BCrypt.Net-Next</AssemblyName>
        <PackageId>BCrypt.Net</PackageId>
        <PackageTags>bcrypt;BCrypt.Net;cryptography;hashing;password;security</PackageTags>
        <PackageReleaseNotes>Corrects usage of Secure random number generator; change secure equals to match .net identity implmentation; inline vars in encipher method; change UTF8 handling to safer default</PackageReleaseNotes>
        <PackageIconUrl>https://raw.githubusercontent.com/BcryptNet/bcrypt.net/master/ico64.png</PackageIconUrl>
        <PackageProjectUrl>https://github.com/BcryptNet/bcrypt.net</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/BcryptNet/bcrypt.net/blob/master/licence.txt,</PackageLicenseUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/BcryptNet/bcrypt.net</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net20' ">
        <Reference Include="System" />
    </ItemGroup>
    <PropertyGroup Condition=" '$(TargetFramework)' == 'net20' ">
        <DefineConstants>$(DefineConstants);LEGACY</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(TargetFramework)' == 'net35' ">
        <DefineConstants>$(DefineConstants);LEGACY</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net35' ">
        <Reference Include="System" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net40' ">
        <Reference Include="System" />
        <Reference Include="Microsoft.CSharp" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(TargetFramework)' == 'net40' ">
        <DefineConstants>$(DefineConstants);LEGACY</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
        <Reference Include="System" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net451' ">
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.0" />
        <Reference Include="System" />
        <Reference Include="Microsoft.CSharp" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net452' ">
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.0" />
        <Reference Include="System" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.0" />
        <Reference Include="System" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.3' ">
        <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
        <PackageReference Include="System.Runtime.Extensions" Version="4.3.0" />
        <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.0" />
        <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.6' ">
        <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
        <PackageReference Include="System.Runtime.Extensions" Version="4.3.0" />
        <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.0" />
        <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">
        <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
        <PackageReference Include="System.Runtime.Extensions" Version="4.3.0" />
        <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.0" />
        <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.0" />
    </ItemGroup>

</Project>
```

![image](https://cloud.githubusercontent.com/assets/83597/23613709/7709c6e6-0278-11e7-8795-d956062ce988.png)

The proj on trying to open runs restore/build and implodes with xml errors as per the screenshot; This might be more to do with nuget but nuget seems to restore fine and its VS that hangs with msbuild running in task manager. Directly calling msbuild against the csproj works fine. So I'm assuming its also with the multi-targeting. I'm unable to get to the build log in the console as VS hangs.

All the parts being separate yet totally reliant on each other its difficult at a glance to pick apart where an issues coming from; more so when VS still locks up on the failure of components.

Ironically (ironic as I have 32gig of ram) VS logs a low memory error;
```
Error Information
AppInsightsEvent Name = vs/perf/lowmemoryreached
          Description = Low memory reached.
     TelemetrySession = 'c0a0e37f-4b0d-4979-a14b-9427ff623bf9' Started = True OptIn=True IsInitialized = True Cloned = False
             UTC time = 2017-03-06T13:51:38

 currently running Stack
    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.SetBucketParametersForNoExceptionFromClr()
    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.SetInitialBucketParameters(Exception exceptionObject)
    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport..ctor(FaultEvent faultEvent, TelemetrySession telemetrySession)
    at Microsoft.VisualStudio.Telemetry.SessionChannel.WatsonSessionChannel.PostEvent(TelemetryEvent telemetryEvent)
    at Microsoft.VisualStudio.Telemetry.TelemetrySession.PostEvent(TelemetryEvent telemetryEvent)
    at Microsoft.Performance.ResponseTime.LowMemoryDumpCollectorFactory.LowMemoryDumpCollector.CollectAndSendDump()
    at Microsoft.Performance.ResponseTime.LowMemoryDumpCollectorFactory.LowMemoryDumpCollector.<>c__DisplayClass3_0.<.ctor>b__0(Object <sender>, ElapsedEventArgs <e>)
    at System.Timers.Timer.MyTimerCallback(Object state)
    at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.TimerQueueTimer.CallCallback()
    at System.Threading.TimerQueueTimer.Fire()
    at System.Threading.TimerQueue.FireNextTimers()
    at System.Threading.TimerQueue.AppDomainTimerCallback()
Telemetry Session Shared Properties:
   VS.Core.User.Location.GeoId = 242
   VS.Core.ExeName = perfwatson2
   VS.Core.BranchName = d15rel
   VS.Core.User.IsOptedIn = True
   VS.Core.User.IsMicrosoftInternal = False
   VS.Core.User.Type = External
   VS.Core.MacAddressHash = 33c53b4344be78ab998a032ed69f431bcf1cb85e9481d6a8c61667126778367b
   VS.Core.OS.Version = 10.0.14393.48
   VS.Core.User.Id = cd3be1d3-9a6b-4104-a945-3f289a3534eb
   VS.Core.Machine.Id = ffcf252f-e0ba-41c5-8c0b-cf2972d6daf9
   VS.Core.User.PersonalizationVsid = 240c54b5-94d4-4868-a396-1c5a50996b1a
   VS.Core.User.IsMicrosoftInternalDeprecated = False
   VS.Core.ExeVersion = 15.0.26206.0
   VS.Core.TelemetryApi.ProductVersion = 15.0.770-master79B7C1EE
   VS.Core.BuildNumber = 26206
Telemetry event 'vs/perf/lowmemoryreached' properties:
   [VS.Fault.WatsonOptIn] = 'CallbackOptIn'
   [VS.Fault.Exception.ModuleVersion] = '15.0.26206.0'
   [VS.Fault.Exception.Offset] = '661'
   [vs.perfwatson2.dumpcollectiontimems] = '5768'
   [VS.Fault.WatsonReportNumber] = '0'
Telemetry event 'vs/perf/lowmemoryreached' reserved properties:
   [DataModel.Severity] = '10'
   [DataModel.Source] = 'DataModelApi'
   [DataModel.EntityType] = 'Fault'
   [DataModel.EntitySchemaVersion] = '4'
   [DataModel.CorrelationId] = '67588653-1a9d-4f2e-9bd5-bba8b5ee109d'
   [DataModel.ProductName] = 'vs'
   [DataModel.FeatureName] = 'perf'
   [DataModel.EntityName] = 'lowmemoryreached'
   [DataModel.Fault.Exception.StackTrace] = '   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.SetBucketParametersForNoExceptionFromClr()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.SetInitialBucketParameters(Exception exceptionObject)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport..ctor(FaultEvent faultEvent, TelemetrySession telemetrySession)
   at Microsoft.VisualStudio.Telemetry.SessionChannel.WatsonSessionChannel.PostEvent(TelemetryEvent telemetryEvent)
   at Microsoft.VisualStudio.Telemetry.TelemetrySession.PostEvent(TelemetryEvent telemetryEvent)
   at Microsoft.Performance.ResponseTime.LowMemoryDumpCollectorFactory.LowMemoryDumpCollector.CollectAndSendDump()
   at Microsoft.Performance.ResponseTime.LowMemoryDumpCollectorFactory.LowMemoryDumpCollector.<>c__DisplayClass3_0.<.ctor>b__0(Object <sender>, ElapsedEventArgs <e>)
   at System.Timers.Timer.MyTimerCallback(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
'
   [DataModel.Fault.Description] = 'Low memory reached.'
   [DataModel.Fault.BucketParam1] = 'devenv.exe'
   [DataModel.Fault.BucketParam2] = '15.0.26206.0'
   [DataModel.Fault.BucketParam3] = 'vs.perf.lowmemoryreached'
   [DataModel.Fault.BucketParam4] = '3072MB'
   [DataModel.Fault.BucketParam5] = '_'
   [DataModel.Fault.BucketParam6] = '_'
   [DataModel.Fault.BucketParam7] = ''
   [DataModel.Fault.BucketParam8] = ''
   [DataModel.Fault.BucketParam9] = ''
   [DataModel.Fault.BucketParam10] = ''
   [DataModel.Fault.IsSampled] = 'True'

   CallStack Hash:6863d261

   Added File C:\Users\chris\AppData\Local\Temp\LowMemoryDump0e78550c-6238-419d-a90b-3a5e48f6519c.dmp



```

**Comment by ChrisMcKee** [comment]
Ok if I leave it, it takes ~9-15 minutes for vs to ungrey itself and the job to complete

The build outputs about 60.8mb so that sorta explains a lot; I've uploaded it to SYNC https://cp.sync.com/dl/cc9a32cc0#mpx5n7ki-9dnnwh92-988zvd85-iv272s2q

Have the VS team not worked out how to call msbuiild without locking the process?

On the upside I got to have some dinner and a brew while it compiled; takes me back to Bordland compiler.

**Comment by ChrisMcKee** [comment]
Issue seems to be resolved in rtm.
