### ISSUE TITLE
`dotnet msbuild` commands sometimes hang after writing MSBuild_*.failure.txt files

### ISSUE THREAD

**Issue by dougbu** [Microsoft/msbuild#1808]
_From @dougbu on February 25, 2017 23:21_

## Steps to reproduce
1. clone the [MVC repo](https://github.com/aspnet/Mvc) (https://github.com/aspnet/Mvc.git)
2. checkout the `dougbu/does.it.hang.yes.it.does` branch
3. initialize the build and restore everything: `.\build.cmd initialize`
4. either use `build.cmd` to compile (this involves wrapper / waiting `sake.exe` and `dotnet` processes) or run inner MsBuild command with stderr redirected. I.e. execute one of
  - `.\build.cmd build-compile`
  - `dotnet msbuild /nologo "C:\dd\dnx\Universe\Mvc\.build/makefile.proj" "/p:LifecycleType=Standard;Configuration=Debug" /t:Compile 2>build.err`

Have similar issues with `2>&1 |tee build.log`, `|tee build.log` or `2>&1` in the second case. The unadorned second command and that with `2>build.err >build.log` usually work fine.

## Expected  behavior
Build completes and exits cleanly.

Errors and warnings during the build are expected as well, especially MSB3277 due to .Microsoft/vstest#393 or perhaps because Mvc.Core project depends on Microsoft.Extensions.DependencyModel version `1.2.0-*` while the xUnit runner uses version `1.1.0`.

## Actual behavior
Commands hang consistently. (Hang may take some work in Task Manager due to dotnet/cli#4856.)

It's not predictable what project is last mentioned in `build.log`. But, hangs seem to occur when the build is near its end.

There's never just one `dotnet` process when hangs occur. Usually see the original command, the `dotnet exec` command (to invoke the latest copy of `dotnet.exe`), and at least one of the worker processes.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004883)

Product Information:
 Version:            1.0.0-rc4-004883
 Commit SHA-1 hash:  fa2c9e025c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\dougbu\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004883
```

## Additional information
I have process dumps captured in Visual Studio and Task Manager. If they will help, contact me at my Microsoft email (same alias as here) and I'll share.

Problems appear specific to this branch. Command-line builds complete reliably in the `dougbu/migration` branch for example. I cleaned up some `dotnet migrate` artifacts in the `dougbu/migration` branch and the `*.sln` files are different. But, largest change is probably a fix that's only in the `dougbu/migration` branch to build just `Mvc.sln` and not all three solutions.

_Copied from original issue: dotnet/cli#5849_

**Comment by dougbu** [comment]
FYI @Eilon this is the hang we discussed a couple of days back.

**Comment by dougbu** [comment]
Behaviour more consistent after I rebased `dougbu/does.it.hang.yes.it.does` to include latest from the Mvc `dev` branch. Problems now sometimes reproduce without redirects. Likely the redirects just change timings slightly and previously made races occur more often.

> But, largest change is probably a fix that's only in the `dougbu/migration` branch to build just Mvc.sln and not all three solutions.

I tested in the `dougbu/migration` branch after backing out that fix. No hangs.

**Comment by dougbu** [comment]
Just saw a message about `MSBuild_*.failure.txt` files written into `$env:temp`. These messages aren't normally output. But, I've got files for all or most hangs I've experienced this morning. Contents include
```
UNHANDLED EXCEPTIONS FROM PROCESS 16096:
=====================
2/27/2017 09:27:51
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.BackEnd.NodePacketTranslator.SerializedException.ToException(SerializedException serializedException)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketReadTranslator.TranslateException(Exception& value)
   at Microsoft.Build.Execution.BuildResult.Microsoft.Build.BackEnd.INodePacketTranslatable.Translate(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketReadTranslator.Translate[T](T& value)
   at Microsoft.Build.BackEnd.BuildRequestUnblocker.Translate(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.BuildRequestUnblocker.FactoryForDeserialization(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.PacketFactoryRecord.DeserializeAndRoutePacket(Int32 nodeId, INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, INodePacketTranslator translator)
   at Microsoft.Build.Execution.OutOfProcNode.Microsoft.Build.BackEnd.INodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, Queue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```
and / or (or is much more common)
```
UNHANDLED EXCEPTIONS FROM PROCESS 16360:
=====================
2/27/2017 09:37:13
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Items already exist for target CoreBuild.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Execution.BuildResult.AddResultsForTarget(String target, TargetResult result)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48.MoveNext()
===================
```

Of course, these failures should not result in hangs.

**Comment by dougbu** [comment]
@pranavkm please add your smaller (IdentityServer) repro steps to this bug.

**Comment by dougbu** [comment]
Renamed issue because redirection is not required to see the hangs.

**Comment by pranavkm** [comment]
Saw this in our CI and locally recently when building this specific commit https://github.com/aspnet/IdentityService/commit/7f3707520cc5bba05947ef8a660b3c41eb5968a7:

1. `src\Microsoft.AspNetCore.Identity.Service\Microsoft.AspNetCore.Identity.Service.csproj` failed to compile due to `TreatWarningsAsErrors`: 
```
ApplicationManager.cs(13,22): error CS0649: Field 'ApplicationManager<TApplication>._disposed' is never assigned to, and will always have its default value false [IdentityService\src\Microsoft.AspNetCore.Identity.Service\Microsoft.AspNetCore.Identity.Service.csproj]
```
2. Projects referencing it failed to build. The error message doesn't seem particularly correct:
```
dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'IdentityService\src\Microsoft.AspNetCore.Identity.Service\Microsoft.AspNetCore.Identity.Service.csproj'. This can indicate a missing project reference. [IdentityService\src\Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore\Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.csproj]
dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'IdentityService\src\Microsoft.AspNetCore.Identity.Service\Microsoft.AspNetCore.Identity.Service.csproj'. This can indicate a missing project reference. [IdentityService\test\Microsoft.AspNetCore.Identity.Service.Test\Microsoft.AspNetCore.Identity.Service.Test.csproj]
```

MSBuild prints this error and ends up hanging. Our CI eventually killed it after 240 minutes of inactivity:
`MSBUILD : error MSB4166: Child node "5" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.`

Failure log file says:
```
UNHANDLED EXCEPTIONS FROM PROCESS 150400:
=====================
3/7/2017 8:41:02 AM
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Items already exist for target CoreBuild.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Execution.BuildResult.AddResultsForTarget(String target, TargetResult result)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48.MoveNext()
===================
```

**Comment by natemcmaster** [comment]
This happened again today with MSBuild 15.2.47.30403 on .NET Core. I've gathered process dumps of MSBuild in its hung state. Let me know if you'd like me to email them to you.

**Comment by mikeharder** [comment]
# Simplified Repro Steps
1. VM with clean Win10
2. Install .NET 4.5.1 and 4.5.2 targeting packs
  A. https://www.microsoft.com/en-us/download/details.aspx?id=40772
  B. https://www.microsoft.com/en-us/download/details.aspx?id=42637
3. Unzip https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005724/dotnet-dev-win-x64.2.0.0-preview1-005724.zip
4. git clone https://github.com/aspnet/IdentityService
5. cd IdentityService
6. git checkout 7f3707520cc5bba05947ef8a660b3c41eb5968a7 (known good commit)
7. ..\dotnet-dev-win-x64.2.0.0-preview1-005724\dotnet.exe restore /p:TargetFrameworks=netcoreapp1.1
8. ..\dotnet-dev-win-x64.2.0.0-preview1-005724\dotnet.exe build /p:TargetFrameworks=netcoreapp1.1

**Comment by dougbu** [comment]
@AndyGerlicher does 1022b48 correct MSBuild hangs in general? Or, is it a targeted fix for hangs during compilation? I ask because we've seen hangs while MSBuild is testing projects and / or without *.failure.txt files.

Sticking to the *.failure.txt cases, does 1022b48 avoid both stack traces shown in my [comment above](https://github.com/Microsoft/msbuild/issues/1808#issuecomment-284806981)?

And, which MSBuild release will include 1022b48?
