### ISSUE TITLE
MSB4018	The "GenerateBindingRedirects" task failed unexpectedly

### ISSUE THREAD

**Issue by deastr** [Microsoft/msbuild#1815]
I just upgraded my VS.NET 2017 RC4 to release version and started to get this error when building:

```
MSB4018	The "GenerateBindingRedirects" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Projects\KYSV3\Source\Identity.Management\Identity.Management.Web.UI\obj\Debug\net452\win10-x64\Identity.Management.Web.UI.csproj.Identity.Management.Web.UI.exe.config'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.Build.Shared.FileUtilities.OpenWrite(String path, Boolean append, Encoding encoding)
   at Microsoft.Build.Tasks.GenerateBindingRedirects.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	

Identity.Management.Web.UI	

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2042	
```

My csproject:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>kdys.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <Target Name="PreBuildOperations" BeforeTargets="PreBuildEvent">
    <Exec Command="echo $(ProjectDir)bin\$(ConfigurationName)\PublishOutput siliniyor." Condition="Exists('$(ProjectDir)bin\$(ConfigurationName)\PublishOutput')" />
    <RemoveDir Directories="$(ProjectDir)bin\$(ConfigurationName)\PublishOutput" Condition="Exists('$(ProjectDir)bin\$(ConfigurationName)\PublishOutput')" />
    <Exec Command="echo $(ProjectDir)obj\$(ConfigurationName)\net452\$(RuntimeIdentifier) siliniyor." Condition="Exists('$(ProjectDir)obj\$(ConfigurationName)\net452\$(RuntimeIdentifier)')" />
    <RemoveDir Directories="$(ProjectDir)obj\$(ConfigurationName)\net452\$(RuntimeIdentifier)" Condition="Exists('$(ProjectDir)obj\$(ConfigurationName)\net452\$(RuntimeIdentifier)')" />
  </Target>

  <Target Name="AfterPublishOperations" AfterTargets="AfterPublish">
    <Exec Command="echo appsettings.$(ConfigurationName).json dosya adı appsettings.json olarak güncelleniyor ve wwwroot'a kopyalanıyor." />
    <Delete Files="$(ProjectDir)bin\$(ConfigurationName)\PublishOutput\appsettings.json" />
    <Copy SourceFiles="$(ProjectDir)bin\$(ConfigurationName)\PublishOutput\appsettings.$(ConfigurationName).json" DestinationFiles="$(ProjectDir)bin\$(ConfigurationName)\PublishOutput\appsettings.json" />
    <Delete Files="$(ProjectDir)bin\$(ConfigurationName)\PublishOutput\appsettings.$(ConfigurationName).json" />
    <Copy SourceFiles="$(ProjectDir)bin\$(ConfigurationName)\PublishOutput\appsettings.json" DestinationFiles="$(ProjectDir)bin\$(ConfigurationName)\PublishOutput\wwwroot\appsettings.json" OverwriteReadOnlyFiles="true" />
  </Target>

  <Target Name="AfterBuildOperations" AfterTargets="AfterBuild">
    <Exec Command="echo appsettings.json wwwroot'a kopyalanıyor." />
    <Copy SourceFiles="$(ProjectDir)appsettings.json" DestinationFiles="$(ProjectDir)wwwroot\appsettings.json" OverwriteReadOnlyFiles="true" />
  </Target>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Remove="wwwroot/appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Identity.Management.Web.UI.csproj.vspscc" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
```

```
>dotnet --info
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by deastr** [comment]
The problem is with this line, removing it gets rid of the error:

<RemoveDir Directories="$(ProjectDir)obj\$(ConfigurationName)\net452\$(RuntimeIdentifier)" Condition="Exists('$(ProjectDir)obj\$(ConfigurationName)\net452\$(RuntimeIdentifier)')" />
