### ISSUE TITLE
Project Instance cannot load

### ISSUE THREAD

**Issue by ionescuvictor** [microsoft/msbuild#1981]
`ProjectInstance instance = new ProjectInstance(@"E:\consoleVic\ConsoleTryCompile\WebClassLibrary\WebClassLibrary.csproj");`

I get this.
System.IO.FileNotFoundException: 'The system cannot find the file specified. (Exception from HRESULT: 0x80070002)'

I am trying to load a csproj via the project instance, howoever it breaks at probably 'Type.GetType("Mono.Runtime") inside the buildEnvr isMono accessor.GetType does have the IO.FileNotFoundException but only if you specify to throw the error like so. Type.GetType("Mono.RunTime, true).

Funny enough i am unable to check to see if that is the case because i cannot open the MSBUILD solution due to another error.

On another computer it works, however on my home pc, it does not work.

here is the link to my test solution

https://drive.google.com/open?id=0BydA_hdY-trTOXRteTVEVHlPNGc

```

   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsMono()
   at Microsoft.Build.BackEnd.Logging.LoggingService..ctor(LoggerMode loggerMode, Int32 nodeId)
   at Microsoft.Build.Evaluation.ProjectCollection.CreateLoggingService(Int32 maxCPUCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection.get_GlobalProjectCollection()
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile)
   at ConsoleApp1.Program.Main(String[] args) in E:\consoleVic\ConsoleTryCompile\ConsoleApp1\Program.cs:line 14
```

**Comment by AndyGerlicher** [comment]
Team Triage:
It doesn't look like the IsMono is the issue here. And we're not sure what code path here would be throwing that exception in `BuildEnvironmentHelper`. Can you try this with symbols loaded? You should be able to download the symbols from the Microsoft Symbol Server (in the Debugging options) and get a more accurate stack trace.
