### ISSUE TITLE
XmlPoke task not updating an element value

### ISSUE THREAD

**Issue by kichalla** [Microsoft/msbuild#2105]
**Repro:**
- Create a xml file called 'test.xml' with following content
```xml
<Product>
  <Name>Book</Name>
</Product>
```
- Create a project file called 'test.proj' with following content
```xml
<Project>
    <Target Name="Test">
        <XmlPoke
            XmlInputPath="test.xml"
            Query="/Product/Name"
            Value="Car"/>
    </Target>
</Project>
```
- Run `dotnet msbuild /t:Test`

**Expected**
```xml
<Product>
  <Name>Car</Name>
</Product>
```

**Actual**
```xml
<Product>
  <Name>
  </Name>
</Product>
```

**Environment Info**
```
Microsoft (R) Build Engine version 15.3.234.47922 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```
**dotnet --info**
```
.NET Command Line Tools (2.0.0-preview2-006082)

Product Information:
 Version:            2.0.0-preview2-006082
 Commit SHA-1 hash:  6453cb4e15

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\.dotnet\x64\sdk\2.0.0-preview2-006082\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25309-07
  Build    : 41f5fc94eedc889f086800c23f35bf14a8c75a9f
```

**Comment by rainersigwald** [comment]
This is deeply, deeply confusing. I reproduce your reported behavior, and tried stepping through it in a debugger to see where things were going wrong. In XmlPoke, we navigate to XPath matches, and then [assign ](https://github.com/Microsoft/msbuild/blob/f89e2f755736786f929dde805128580a724d4a2f/src/Tasks/XmlPoke.cs#L207)the `InnerXml` of the match to the specified value:

```c#
iter.Current.InnerXml = _value.ItemSpec;
```

In the debugger, this completes without errors, but sets `iter.Current.InnerXml` to nothing, instead of the requested value. I tried to step through the implementation of `XPathNavigator.InnerXml` but couldn't figure out why it wasn't right.

I tried to reproduce this in a standalone app to send a bug report to CoreFX, and I got a different error when reproducing the situation:

```c#
using System;
using System.Xml;
using System.Xml.XPath;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            XmlDocument xmlDoc = new XmlDocument();

            xmlDoc.LoadXml(@"<Product>
  <Name>Book</Name>
</Product>");

            //xmlDoc.FirstChild.FirstChild.InnerXml = "Car";

            XPathNavigator nav = xmlDoc.CreateNavigator();
            XPathExpression expr = nav.Compile("/Product/Name");

            XPathNodeIterator iter = nav.Select(expr);
            iter.MoveNext();

            Console.WriteLine(iter.Current.InnerXml);

            iter.Current.InnerXml = "Car";

            Console.WriteLine(iter.Current.InnerXml);
        }
    }
}
```

produces

```
S:\work\innerxml_assignment\ConsoleApp1\ConsoleApp1>dotnet run
Book

Unhandled Exception: System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathNavigator.BuildSubtree(XmlReader reader, XmlWriter writer)
   at System.Xml.XPath.XPathNavigator.AppendChild(XmlReader newChild)
   at ConsoleApp1.Program.Main(String[] args)
```

Ok, _that's_ confusing. So I tried running MSBuild with `dotnet exec path\to\fresly\built\msbuild.dll` and see the same error!

```
s:\work\xmlpoke>dotnet\dotnet.exe exec S:\msbuild\bin\Debug-NetCore\Windows_NT_Deployment\\MSBuild.dll test.proj
Waiting for debugger to attach (s:\work\xmlpoke\dotnet\dotnet.exe PID 27052).  Press enter to continue...

Microsoft (R) Build Engine version 15.3.0.0 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/17/2017 5:52:28 PM.
Project "s:\work\xmlpoke\test.proj" on node 1 (default targets).
s:\work\xmlpoke\test.proj(3,9): error MSB3735: Error while executing poke operation with the Value parameter "Car". Data at the root level is invalid. Line 1, position 1.
Done Building Project "s:\work\xmlpoke\test.proj" (default targets) -- FAILED.


Build FAILED.

"s:\work\xmlpoke\test.proj" (default target) (1) ->
(Test target) ->
  s:\work\xmlpoke\test.proj(3,9): error MSB3735: Error while executing poke operation with the Value parameter "Car". Data at the root level is invalid. Line 1, position 1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.87
```

This makes me suspect an issue with the different runtime that the CLI provides for us.

**Comment by ncsurfus** [comment]
This definitely seems related to .NET Core. I had the same issue when running dotnet build from the command line, but I noticed I didn't have the issue when building from Visual Studio 2017. The version appears the same, but dotnet is .NET Core and VS is .NET Framework.

```
> dotnet msbuild /version
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.3.409.57025
```
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin>msbuild /version
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.3.409.57025
```

**Comment by davisnw** [comment]
I still seem to be seeing this problem 3 year later...
