### ISSUE TITLE
GenerateResource in UWP project Error when using stream resources in the resx files

### ISSUE THREAD

**Issue by tarekgh** [Microsoft/msbuild#2248]
[UWP-Win8.zip](https://github.com/Microsoft/msbuild/files/1106537/UWP-Win8.zip)

When having UWP project which is reference a C# portable library that is using stream resources in the resx file and then compiling the UWP project will get the following error

```
Error		The "GenerateResource" task failed unexpectedly.
System.InvalidOperationException: Item named 'SerializedStream' of type 'System.IO.UnmanagedMemoryStream' cannot be added to the resource file because it is not serializable.
   at Microsoft.Build.Tasks.ProcessResourceFiles.WriteResources(ReaderInfo reader, IResourceWriter writer)
   at Microsoft.Build.Tasks.ProcessResourceFiles.WriteResources(ReaderInfo reader, String filename)
   at Microsoft.Build.Tasks.ProcessResourceFiles.ProcessFile(String inFile, String outFileOrDir)
   at Microsoft.Build.Tasks.ProcessResourceFiles.Run(TaskLoggingHelper log, ITaskItem[] assemblyFilesList, List`1 inputs, List`1 satelliteInputs, List`1 outputs, Boolean sourcePath, String language, String namespacename, String resourcesNamespace, String filename, String classname, Boolean publicClass, Boolean extractingResWFiles, String resWOutputDirectory)
   at Microsoft.Build.Tasks.ProcessResourceFiles.Run(TaskLoggingHelper log, ITaskItem[] assemblyFilesList, List`1 inputs, List`1 satelliteInputs, List`1 outputs, Boolean sourcePath, String language, String namespacename, String resourcesNamespace, String filename, String classname, Boolean publicClass, Boolean extractingResWFiles, String resWOutputDirectory)
   at Microsoft.Build.Tasks.GenerateResource.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	UWP-Win8	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets	1189	
```

I didn't notice getting same error if I create a desktop app instead.

**Comment by tarekgh** [comment]
a side note, I am raising this issue because this scenario will become a valid scenario for netstandard 2.0 as we'll expose the API's that can read the stream resources (using ResourceManager class)

**Comment by dsplaisted** [comment]
I think there are a lot of assumptions across the tooling that portable, .NET Standard, or .NET Core projects only support string resources. If you intend to change that you need to talk to at least there project system and CLI/SDK teams (and probably msbuild too).

Sent from my Windows 10 phone

**Comment by tarekgh** [comment]
> I think there are a lot of assumptions across the tooling that portable, .NET Standard, or .NET Core projects only support string resources.

String resources are supported to be accessed through the PRI. but other resources should be supported inside the managed image which you can get into it using Assembly.GetManifestResourceStream. 
msbuild task shouldn't fail anyway even if this resource is not supported as it shouldn't do anything with it. I opened the issue here so we can start fixing it in msbuild as the failing task belong to msbuild
