### ISSUE TITLE
GenerateResource cannot extract resources from ARM binaries

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#2253]
This was reported via feedback as https://developercommunity.visualstudio.com/content/problem/54934/uwp-resx-strings-not-merged-into-the-pri-file-for.html and as https://connect.microsoft.com/VisualStudio/feedback/details/2345310/. Internal bug [189984](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/189984).

If a UWP app project that builds an appx package refers to a DLL compiled for ARM that embeds resources, those resources are silently ignored rather than packaged into the PRI.

This is because of a `BadImageFormatException`

```
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.UnsafeLoadFrom(String assemblyFile)
   at Microsoft.Build.Tasks.ProcessResourceFiles.ReadAssemblyResources(String name, String outFileOrDir) in E:\A\_work\8\s\src\Tasks\GenerateResource.cs:line 2958
```
 
Thrown [here ](https://github.com/Microsoft/msbuild/blob/f45785fb104c30080024affe855cd10ad27c6d4e/src/Tasks/GenerateResource.cs#L2958) and silently ignored [here](https://github.com/Microsoft/msbuild/blob/f45785fb104c30080024affe855cd10ad27c6d4e/src/Tasks/GenerateResource.cs#L2997-L3003).

**Comment by rainersigwald** [comment]
## Workaround

Compile the libraries to AnyCPU rather than ARM.

**Comment by ericstj** [comment]
I suspect the fix here is to move that task to use a metadata reader rather than reflection.  Typically its bad-news for build tools to use reflection/assembly.load since those have parity with the build-time framework not the targeted framework.

**Comment by rainersigwald** [comment]
@ericstj Yes, I've been asking for help with that approach, because as far as I can tell `System.Reflection.Metadata` doesn't expose enough information: https://github.com/Microsoft/msbuild/pull/2254#discussion_r129891209.

**Comment by ericstj** [comment]
Ah, I missed that.  I've added some info.  S.R.M is a bit confusing sometimes since it's much lower in the stack.  I suspect you need to get a binary blob and wrap that in a stream.
