### ISSUE TITLE
Assembly loading issue.

### ISSUE THREAD

**Issue by keeper013** [Microsoft/msbuild#2341]
I have a console application targeted to build with net461 and netcoreapp2.0. Build is successful, and the program can run with both target frameworks. Then I tried to expose a custom task from the very same assembly to do the same thing, tried to trigger it in a csproj file with the following code:

```xml
<UsingTask AssemblyFile="D:\testPublish\publish\CrossCutterN.Console.exe" TaskName="CrossCutterN.Console.MsBuild.Weave" />
  <Target Name="WeaveTest" AfterTargets="Build">
    <ItemGroup>
      <AspectBuilderConfigFiles Include="$(MSBuildThisFileDirectory)..\CrossCutterN.Console\$(OutDir)aspectBuilder.json" />
    </ItemGroup>
    <ItemGroup>
      <AdviceConfigFiles Include="$(TargetDir)advice.json" />
    </ItemGroup>
    <ItemGroup>
      <TargetConfigFiles Include="$(TargetDir)target.json" />
    </ItemGroup>
    <Weave AspectBuilderConfigFiles="@(AspectBuilderConfigFiles)" AdviceConfigFiles="@(AdviceConfigFiles)" TargetConfigFiles="@(TargetConfigFiles)" />
```

Then assembly loading issue happens:

```
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at CrossCutterN.Console.Application.ConfigurationProcessor.Process(String[] paths) in D:\CrossCutterN-net-core\CrossCutterN.Console\Application\ConfigurationProcessor.cs:line 24
   at CrossCutterN.Console.Application.ConsoleApplication.GetAspectBuilderUtility(String[] aspectBuilderConfigurations) in D:\CrossCutterN-net-core\CrossCutterN.Console\Application\ConsoleAppilcation.cs:line 57
   at CrossCutterN.Console.Application.ConsoleApplication.Process(String[] aspectBuilderConfigFiles, String[] adviceConfigFiles, String[] targetConfigFiles) in D:\CrossCutterN-net-core\CrossCutterN.Console\Application\ConsoleAppilcation.cs:line 36
       Done executing task "Weave".
```

What I don't understand is in the project, the version of NewtonSoft.Json referenced is 10.0.1, and the assembly having this reference is Microsoft.Extensions.Configuration.Json, version is 2.0.0-preview2-final.

If directly executed from D:\testPublish\publish\ folder, both net461 and netcoreapp2.0 have no problems.

**Comment by ac3ju** [comment]
Hi,
Did you solve it ?

**Comment by keeper013** [comment]
Hi:
I haven't been working on this for quite a long time, msbuild is not a focus of my project anymore. So this is not so important to me now.
