### ISSUE TITLE
wildcard src\**\*.*proj not being expanded

### ISSUE THREAD

**Issue by kingerja** [Microsoft/msbuild#2452]
When an invalid symlink folder exist under a path to be expanded line 194 in FileMatcher.cs throws which is then caught and wildcard expansion is not done due to it.

Certain build engines will create TestSandbox folders on failed unit test and if the user goes and deletes the location to where the sandbox points to any future builds of their enlistment will fail.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Microsoft.Build.Shared.FileMatcher.GetAccessibleFiles(String path, String filespec, String projectDirectory, Boolean stripProjectDirectory) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 194
   at Microsoft.Build.Shared.FileMatcher.GetAccessibleFileSystemEntries(FileSystemEntity entityType, String path, String pattern, String projectDirectory, Boolean stripProjectDirectory) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 121
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursiveStep(RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 846
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 710
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 805
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 805
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 805
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 805
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 805
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 805
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, GetFileSystemEntries getFileSystemEntries, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 805
   at Microsoft.Build.Shared.FileMatcher.GetFiles(String projectDirectoryUnescaped, String filespecUnescaped, IEnumerable`1 excludeSpecsUnescaped, GetFileSystemEntries getFileSystemEntries, DirectoryExists directoryExists) in d:\git\MSBuild\src\Shared\FileMatcher.cs:line 1813

**Comment by michael-baker** [comment]
I have this issue but without the exception. 

Under MSBuild 14.0 if I have a globbing pattern that encounters a directory that contains a broken symlink the wild card simply doesn't get expanded which then crashes the build in other ways as the ItemGroup that contains the expression contains "**" which is not a valid win32 path.

Create a broken link like this

`cmd /c mklink /D foo ..\..\tmp`

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="14.0">

  <PropertyGroup>
    <SolutionRoot>C:\Temp</SolutionRoot>
  </PropertyGroup>

  <Target Name="GrovelForExtensibilityFiles">

    <ItemGroup>
      <ExtensibilityFiles Include="$(SolutionRoot)**\dir.props"
                          Exclude="$(SolutionRoot)packages;
                                   $(SolutionRoot)Dependencies" />
    </ItemGroup>
    
    <Message Text="%(ExtensibilityFiles.FullPath)" />

  </Target>  
</Project>
```


This ouputs

> GrovelForExtensibilityFiles:
>   C:\Temp**\dir.props

**Comment by rainersigwald** [comment]
See also #3642 and #406.
