### ISSUE TITLE
MSBuild System.TypeInitializationException

### ISSUE THREAD

**Issue by sayah0imad** [Microsoft/msbuild#2770]
j'ai crée un projet UWP Fall Creator Update avec une tache qui se declanche lors du build du projet . 

j'ai u un message d'erreur disant  : 

(System.TypeInitializationException) An exception was thrown by the type initializer for 'Microsoft.Build.Internal.AvailableStaticMethods'

**Comment by sayah0imad** [comment]
FY 
that happend when i update my vs2017 to 15.4.4 , knowing that it works well before .
thank's

**Comment by itrice** [comment]
I have a similar problem. 
command: msbuild.exe /version
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Build.CommandLine.MSBuildApp' threw an exception. ---> System.FieldAccessException: Attempt by method 'Microsoft.Build.CommandLine.MSBuildApp..cctor()' to access field 'Microsoft.Build.Shared.MSBuildConstants.EqualsChar' failed.
   at Microsoft.Build.CommandLine.MSBuildApp..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```
And I cann't use VS2019. Even the app based on .net framework.

**Comment by YuliiaKovalova** [comment]
It looks like a stale issue.
Please submit a new one if it happens again.
