### ISSUE TITLE
System.TypeInitializationException when building projects after 15.5 update

### ISSUE THREAD

**Issue by jicata** [microsoft/msbuild#2801]
### Summary

After updating to latest version of MSBuild 15.5.180.51428 via the Visual Studio Installer **not a single project** can be built with MSBuild. Exception being thrown:

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.TypeInitializationException: The type initializer for 'Microsoft.Build.Shared.NativeMethodsShared' threw an exception. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.

### Steps to reproduce

1. Update to latest version of MSBuild
2. Try to build any existing project with `msbuild.exe <projectName>.csproj` for example

### Expected  behavior
Being able to build a project using MSBuild.exe

### Actual behavior
A System.TypeInitializationException is being thrown

`msbuild <projectName>.csproj`

![image](https://user-images.githubusercontent.com/5772421/33933331-0befa31c-dffe-11e7-9f14-af8fb599d48d.png)

**New project in VS**
![image](https://user-images.githubusercontent.com/5772421/33932834-b59502d8-dffc-11e7-9d5f-9c18087d72b5.png)

**Solution Explorer in VS**
![image](https://user-images.githubusercontent.com/5772421/33932830-b309044c-dffc-11e7-8856-0f2296d6c367.png)

**Trying to Reload a project in VS**
![image](https://user-images.githubusercontent.com/5772421/33932866-cd3cf062-dffc-11e7-98ee-cbe3dfa4f9dd.png)

### Environment data
MSBuild version : Build Engine version 15.5.180.51428 for .NET Framework
Output: 
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.TypeInitializationException: The type initializer for 'Microsoft.Build.Shared.NativeMethodsShared' threw an exception. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.InteropServices.OSPlatform.get_Linux()
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsLinux()
   at Microsoft.Build.Shared.NativeMethodsShared..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsMono()
   at Microsoft.Build.BackEnd.Logging.LoggingService..ctor(LoggerMode loggerMode, Int32 nodeId)
   at Microsoft.Build.Evaluation.ProjectCollection.CreateLoggingService(Int32 maxCPUCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Shared.NativeMethodsShared' threw an exception. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.InteropServices.OSPlatform.get_Linux()
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsLinux()
   at Microsoft.Build.Shared.NativeMethodsShared..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsMono()
   at Microsoft.Build.BackEnd.Logging.LoggingService..ctor(LoggerMode loggerMode, Int32 nodeId)
   at Microsoft.Build.Evaluation.ProjectCollection.CreateLoggingService(Int32 maxCPUCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()

**OS info:**
Windows specifications
Edition: Windows 10 Enterprise
Version: 1709
OS Buld: 16299.98

Some additional notes. Visual studio can't load or create any projects either after the update. Also older versions of MSBuild work just fine. I haven't fiddled with my OS in any way other than installing the standard MS updates whenever prompted.

So far I have tried:
Repairing VS
Reinstalling VS
Reinstalling VS Installer
Manually uninstalling/installing MSBuild Tools (which includes msbuild.exe)
Running older versions of MSBuild (this has worked)

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.
