### ISSUE TITLE
How do I use `Microsoft.Build` within my app to load a project?

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/msbuild#2839]
I want to use the `Microsoft.Build` nuget package in a .NET Core app to load a project file. I do not have Visual Studio installed. I am only using the dotnet cli.

### Steps to reproduce

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="15.5.180" />
  </ItemGroup>

</Project>
```

Directory contents:
```
/
- my-app.csproj
- Program.cs
```

Program.cs:
```csharp
using System;
using System.IO;
using Microsoft.Build.Evaluation;
using Microsoft.Build.Construction;
 
class Program
{
    static void Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.WriteLine("Usage: dotnet behave <project>");
            return;
        }
 
        var proj = new Project(Path.GetFullPath(args[0]));
        
        Console.WriteLine(proj);
    }
}
```

Command line
```
dotnet run ../other/other.csproj
```

### Expected  behavior
I can load the CS project file

### Actual behavior

Initially:
```
Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  /path/to/other/other.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) in E:\A\_work\17\s\src\Shared\ProjectErrorUtilities.cs:line 440
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2412
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2215
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2070
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 1006
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 794
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2641
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2634
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2711
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 512
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 410
   at Program.Main(String[] args) in /path/to/my-app/Program.cs:line 16
```

After setting `MSBuildSDKsPath=/usr/local/share/dotnet/sdk/2.1.3/Sdks` and `MSBuildExtensionsPath=/usr/local/share/dotnet/sdk/2.1.3`:
```
Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "/path/to/my-app/bin/Debug/netcoreapp2.0/Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  /usr/local/share/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) in E:\A\_work\17\s\src\Shared\ProjectErrorUtilities.cs:line 440
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, StringunescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2641
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2422
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2215
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2070
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 1109
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2070
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 1175
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 794
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2641
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2634
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2711
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 512
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion) in E:\A\_work\17\s\src\Build\Definition\ProjectCollection.cs:line 1122
   at MSBuildDumper.Main(String[] args) in /path/to/my-app/Program.cs:line 18
```

### Environment data
`dotnet --version`: 2.1.3

OS info: Mac

**Comment by mfilippov** [comment]
@firelizzard18 You should set own SDK resolver or use ```https://github.com/Microsoft/msbuild/blob/497d797007410f43e1d7501b7d8254313b07b2a7/src/Build/BackEnd/Components/SdkResolution/DefaultSdkResolver.cs``` and put Sdk into correctly place. Also you can use SDK resolver from .NET CLI.

**Comment by firelizzard18** [comment]
How would I set my own resolver? Looking through the source of `Microsoft.Build.Evaluation.Project`, I can find no way to alter how it resolves SDKs.

**Comment by dazinator** [comment]
I am having a similar problem, I am using `15.6.82`.

My project file looks like this:

```
<Project Sdk="DnnVs.Sdk">
</Project>
```

In the parent directory of the project file, I have a `Nuget.config` file that looks like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <packageSources> 
    <add key="local-packages" value="local-packages" />   
    <add key="msbuild" value="https://dotnet.myget.org/F/msbuild/api/v3/index.json" />      
  </packageSources>
</configuration>
```

In the "local-packages" folder I have the SDK nuget package that I am wanting to be resolved.

The message I get when I try to load this project
>  Message: Microsoft.Build.Exceptions.InvalidProjectFileException : The SDK 'Foo.Sdk' specified could not be found.  E:\Repos\DnnVsProjectSystem\src\Foo\TestFoo\AddsTargetAssembly.xml

The variables I am using to build with:

- VSINSTALLDIR = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community";
- VisualStudioVersion = "15.0";
- MSBuildSDKsPath = @"C:\Program Files\dotnet\sdk\2.0.0\Sdks\";

**Comment by dazinator** [comment]
Also I notice SdkResolvers folder @ `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\SdkResolvers` and another at the `MSBuildSDKsPath` under `C:\Program Files\dotnet\sdk\2.0.0\Sdks`.  Is it possible for me to use the Visual Studio SDK resolvers? Is there some environment variable or something to control where MsBuild tries to locakte the SdkResolvers?

**Comment by dazinator** [comment]
I am not sure what has changed, but this has started working for me today. The nuget based sdk resolver suddenly finds and restored my sdk package. The only thing I can think of is either that a recent VS upgrade fixed it, or perhaps it was related to nuget cache.
