### ISSUE TITLE
Bootstrapped TaskHostTask seems to be loading assemblies from wrong location

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#2865]
With the toolset changes for #2706, I was getting the following failure in the bootstrapped build:

> C:\git\msbuild\artifacts\Debug\bootstrap\net46\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2979,5): error MSB4018: The "GenerateResource" task failed unexpectedly.
This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
System.TypeInitializationException: The type initializer for 'Microsoft.Build.Shared.BuildEnvironmentHelper' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.BuildEnvironmentHelper.CheckIfRunningTests() in /_/src/Shared/BuildEnvironmentHelper.cs:line 318
   at Microsoft.Build.Shared.BuildEnvironmentHelper..cctor() in /_/src/Shared/BuildEnvironmentHelper.cs:line 391
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Utilities.Traits.get_Instance() in /_/src/Shared/Traits.cs:line 22
   at Microsoft.Build.Shared.NativeMethodsShared.GetLastWriteFileUtcTime(String fullPath) in /_/src/Shared/NativeMethodsShared.cs:line 874
   at Microsoft.Build.Tasks.GenerateResource.ShouldRebuildResgenOutputFile(String sourceFilePath, String outputFilePath) in /_/src/Tasks/GenerateResource.cs:line 1367
   at Microsoft.Build.Tasks.GenerateResource.GetResourcesToProcess(List`1& inputsToProcess, List`1& outputsToProcess, List`1& cachedOutputFiles) in /_/src/Tasks/GenerateResource.cs:line 1273
   at Microsoft.Build.Tasks.GenerateResource.Execute() in /_/src/Tasks/GenerateResource.cs:line 698
   at Microsoft.Build.CommandLine.OutOfProcTaskAppDomainWrapperBase.InstantiateAndExecuteTask(IBuildEngine oopTaskHostNode, LoadedType taskType, String taskName, String taskLocation, String taskFile, Int32 taskLine, Int32 taskColumn, AppDomainSetup appDomainSetup, IDictionary`2 taskParams) [C:\git\msbuild\src\MSBuild\MSBuild.csproj]

The `NullReferenceException` was here:

```C#
var testInfoType = frameworkAssembly.GetType("Microsoft.Build.Framework.TestInfo");
var runningTestsField = testInfoType.GetField("s_runningTests", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);
```

This seems to indicate that it was loading a version of Microsoft.Build.Framework which didn't include the new `TestInfo` type.

As a workaround, I set the following in `src/Directory.Build.props`:

```xml
<GenerateResourceMSBuildArchitecture>CurrentArchitecture</GenerateResourceMSBuildArchitecture>
<GenerateResourceMSBuildRuntime>CurrentRuntime</GenerateResourceMSBuildRuntime>
```

It would be good to investigate what happened here and remove the workaround.

**Comment by YuliiaKovalova** [comment]
The bootstrap was revoked recently, feel free to fill a new bug if it's still relevant to you.
