### ISSUE TITLE
Overflow when coercing arguments crashes MSBuild

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#2882]
### Steps to reproduce

Project file
```xml
<Project>
  <PropertyGroup>
    <X>-2010</X>
  </PropertyGroup>
  <Target Name="Build">
    <Message Text="$([System.Math]::Max($(X), 0))" Importance="high" />
  </Target>
</Project>
```

Stack:
```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.OverflowException: Value was either too large or too small for a signed byte.
   at System.SByte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToSByte(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.CoerceArguments(Object[] args, ParameterInfo[] parameters)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.LateBindExecute(Exception ex, BindingFlags bindingFlags, Object objectInstance, Object[] args, Boolean isConstructor)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
...
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: System.OverflowException: Value was either too large or too small for a signed byte.
...
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

**Comment by KirillOsenkov** [comment]
There are numerous issues uncovered by this repro at various levels. I will be sending a series of PRs to plug all the holes.

1. Convert.ChangeType can throw OverflowException, which isn't handled here: https://github.com/Microsoft/msbuild/blob/91c86a746b312fce1aba31f8fb8540e949c11a01/src/Build/Evaluation/Expander.cs#L3852 (see also: https://msdn.microsoft.com/en-us/library/ms130977(v=vs.110).aspx#Anchor_1)
2. None of the catch blocks above it capture it as well, so it bubbles all the way up and crashes the process
3. In real world multi-proc builds a symptom can be a failed build with no errors and nothing in the log.
4. There should be a well-known function shortcut for Max so that we never have to try the 70 methods on System.Math.

The bug was discovered by analyzing a failing Roslyn build where there are no errors and nothing in the log, but the build fails. The usage of Max was introduced in this commit:
https://github.com/dotnet/roslyn/commit/56ec3cfa6ede7c45dc9bc1ca53c07f6243d8e016

**Comment by KirillOsenkov** [comment]
`ReportResultAndCleanup()` doesn't do anything with an unhandled exception:
http://source.dot.net/#Microsoft.Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs,206d094fa75d32c8

It should log an error as the build request failed. I bet this is the source of all issues we see where the build fails but there were no errors and there is nothing in the log.

**Comment by KirillOsenkov** [comment]
This stack should have logged the exception, but didn't:
```
>	Microsoft.Build.BackEnd.BuildRequestEntry.Complete Line 570	C#	Symbols loaded.
 	Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp Line 846	C#	Symbols loaded.
 	Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport Line 798	C#	Symbols loaded.
 	Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc Line 704	C#	Symbols loaded.
 	Microsoft.Build.BackEnd.RequestBuilder.StartBuilderThread.AnonymousMethod__44_2 Line 627	C#	Symbols loaded.
```
