### ISSUE TITLE
Creating a Microsoft.Build.Evaluation.Project with an SDK fails with an "Internal MSBuild Error"

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2997]
Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.6.0 Preview 5.0 [27411.0.d15.6]

1. Run the following:

``` C#

           var projectRootElement = @"
<Project Sdk=""Microsoft.NET.Sdk"">

</Project>"

            var stringReader = new System.IO.StringReader(projectRootElement);
            var xmlReader = new XmlTextReader(stringReader);
            var root = ProjectRootElement.Create(xmlReader);
            var project = new Project(root);
```

```
Result StackTrace:	
at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Shared.AssemblyResources.GetStringFromEngineResources(String name)
   at Microsoft.Build.Shared.AssemblyResources.GetString(String name)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogWarningFromText(BuildEventContext buildEventContext, String subcategoryResourceName, String warningCode, String helpKeyword, BuildEventFileInfo file, String message)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogWarning(BuildEventContext buildEventContext, String subcategoryResourceName, BuildEventFileInfo file, String messageResourceName, Object[] messageArgs)
   at Microsoft.Build.BackEnd.SdkResolverLoader.LoadResolvers(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.Initialize(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.GetSdkPath(SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly, SdkResolution sdkResolution)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml)
   at Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.OrderingHelperTests.MoveDownFolder_ContainsNestedFolder_IsSuccessful()
Result Message:	Microsoft.Build.Shared.InternalErrorException : MSB0001: Internal MSBuild Error: Missing resource ''
```

This is failing all our tests that use MSBuild.

**Comment by davkean** [comment]
@jeffkl Was there any changes around this?

**Comment by jeffkl** [comment]
> Was there any changes around this?

I sort of rewrote the whole thing in 15.6...

It looks like from the stack trace that MSBuild is trying to log a warning from an embedded resource string but the resource was not found.  What is the layout of your assemblies?  Do you have `en\Microsoft.Build.resources.dll`?

I'll also see if I can repro the problem.

**Comment by jeffkl** [comment]
Hmm another thing is the stack trace doesn't make sense.  The `Microsoft.Build.BackEnd.SdkResolution` class does not exist anymore.  Are you sure your `Microsoft.Build.dll` is 15.6?

This is the only `LogWarning` call in the now deleted class:

https://github.com/Microsoft/msbuild/blob/d026eba43c429802f14ad4bfe57b18e56d2519c7/src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs#L49

My commit on Jan 8 to improve SDK resolution https://github.com/Microsoft/msbuild/commit/03d1435c95e6a85fbf949f94958e743bc44c4186

**Comment by dazinator** [comment]
I am using `15.1.548` and have started seeing this since updating my VS to 15.6. Not sure if thats a coincidence

Output:

> Test Name:	DnnVsProjectSystem.BuildTools.Tests.ManifestBuildTests.Replaces_Tokens_In_Manifest
Test FullName:	DnnVsProjectSystem.BuildTools.Tests.ManifestBuildTests.Replaces_Tokens_In_Manifest
Test Source:	E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\ManifestBuildTests.cs : line 88
Test Outcome:	Failed
Test Duration:	0:00:01.462

Result StackTrace:	
at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Shared.AssemblyResources.GetStringFromEngineResources(String name)
   at Microsoft.Build.Shared.AssemblyResources.GetString(String name)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogWarningFromText(BuildEventContext buildEventContext, String subcategoryResourceName, String warningCode, String helpKeyword, BuildEventFileInfo file, String message)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogWarning(BuildEventContext buildEventContext, String subcategoryResourceName, BuildEventFileInfo file, String messageResourceName, Object[] messageArgs)
   at Microsoft.Build.BackEnd.SdkResolverLoader.LoadResolvers(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.Initialize(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.GetSdkPath(SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly, SdkResolution sdkResolution)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName)
   at DnnVsProjectSystem.BuildTools.Tests.MsBuildHelper.Build(String fileName, Action`1 configure, String& consoleOutput) in E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\Util\MsBuildHelper.cs:line 108
   at DnnVsProjectSystem.BuildTools.Tests.ManifestBuildTests.BuildTestProject(String projectFileName, Boolean assertIsSuccess, Action`1 onBeforeBuild, String& consoleOutput) in E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\ManifestBuildTests.cs:line 198
   at DnnVsProjectSystem.BuildTools.Tests.ManifestBuildTests.WhenProjectIsBuilt(String projectName, Boolean assertSuccess, Action`1 assert) in E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\ManifestBuildTests.cs:line 136
   at DnnVsProjectSystem.BuildTools.Tests.ManifestBuildTests.Replaces_Tokens_In_Manifest() in E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\ManifestBuildTests.cs:line 89
Result Message:	Microsoft.Build.Shared.InternalErrorException : MSB0001: Internal MSBuild Error: Missing resource ''

**Comment by jeffkl** [comment]
@dazinator the stack trace references a class that no longer exists.  Are you sure you're running the latest MSBuild?  When you compile your app, are you getting the assemblies from a NuGet package?

**Comment by dazinator** [comment]
Here is some more info:

I see this error thrown when trying to load an sdk style proj file into a ProjectCollection during a unit test. 

My unit test project is xunit and targets net461.

It has a project reference to the project containing the msbuild task that it is testing. 

The test first does some "prep" work by attempting to build the task project itself (which I also have open in VS) and then pack the task project in order to produce a nuget package with a packageversion that the test has supplied. The test then generates a proj file that has a package reference to the nuget package with the version it created in the previous step. The test then restores this test proj file and then builds the test proj file - and then asserts on the output of the build to see if the msbuild task contained in the package did its job.

The msbuild task project is compiled against :-

- Microsoft.Build.Framework `15.1.548`
- Microsoft.Build.Utilities.Core `15.1.548`

My test project actually pulls in a higher version of those msbuild packages plus a couple exrtra:

- Microsoft.Build.Framework `15.3.409`
- Microsoft.Build.Utilities.Core `15.3.409`
- Microsoft.Build.Tasks.Core `15.3.409`
- Microsoft.Build `15.3.409`

..and then uses an app.config binding redirect to downgrade the `MsBuild.Framework` binary to `newVersion=15.1.0`

This was a workaround after many many attempts at trying to load an SDK style project file using msbuild nuget packages, unsuccessfully, this was the only approach I could find that worked.

When the test runs it also has to set the following Environment Variables before trying to load a project with msbuild, otherwise I was seeing all sorts of other problems raised elsewhere about not being able to find certain paths:

```
                    Environment.SetEnvironmentVariable("VSINSTALLDIR", "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community"):

            Environment.SetEnvironmentVariable("VisualStudioVersion", "15.0");

```

This test has been running fine, but like I say, today it has started breaking when trying to load an sdk style project, and the only thing I can think of that has changed is the vs upgrade. Perhaps I am missing something!

**Comment by jeffkl** [comment]
@dazinator Is there anyway you can use something like fusion log viewer or procmon to verify which `Microsoft.Build.dll` is being loaded?  Its definitely not loading the one you installed with 15.6 because the class in the stack trace is long gone.  It could be a bug in 15.3 that we've fixed but the mystery is still why it started to manifest all of a sudden.  I haven't been able to repro the issue.

@davkean Are you still hitting this?

**Comment by kasper3** [comment]
@dazinator, maybe one more attempt and try compiling against 15.6.82 from NuGet (released 8 days ago) or 15.7.0-preview-000066 from myget (released 12 hours ago) to see if the problem persists. 
For myget preview, add msbuild feed as [additional sources](https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild#project-properties):

```xml
<PropertyGroup>
  <RestoreAdditionalProjectSources>https://dotnet.myget.org/F/msbuild/api/v3/index.json</RestoreAdditionalProjectSources>
</PropertyGroup>
```

**Comment by jeffkl** [comment]
I have figured out the problem.  MSBuild 15.3 shipped with two bugs in the SDK resolver loader logic:

1. When searching for classes in an SDK resolver, `abstract` classes [were not filtered out](https://github.com/Microsoft/msbuild/blob/v15.3.409.57025/src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs#L44).  If an SDK resolver had a class that inherited `SdkResolver` but was `abstract`, it would attempt to create an instance of the `abstract` class and throw an exception
2. The above exception would be caught and logged as a warning but the `LogWarning` call passed `String.Empty` instead of null which would throw an internal error which is treated as a fatal MSBuild error

We fixed the two bugs in MSBuild 15.6 but we also shippped a NuGet-based SDK resolver which has a public `abstract` class that inherits from `SdkResolver`. 

Your unit tests are using MSBuild 15.3 to create an MSBuild environment but are pointing to the installation of MSBuild 15.6.  The logic in `Microsoft.Build.dll` is loading SDK resolvers from the installed location and so you hit these bugs.

You can update your references to the latest MSBuild which will fix the issue.  We cannot patch 15.3 to fix the bugs and we can't patch 15.6 to remove the `abstract` class that is causing the bugs to manifest.

In some cases, it might be best to use [MSBuildLocator](https://github.com/Microsoft/MSBuildLocator) instead which finds and loads the `Microsoft.Build.dll` from the installed location rather than your output directory.  This means that even if you're compiled against an older version, you'll be running the latest `Microsoft.Build.dll`.

FYI @AndyGerlicher

**Comment by dazinator** [comment]
@jeffkl  Thank you for investigating and I am glad for the answer.
I will try what you have suggested, MSBuildLocator seems like a good way forward.

On a slight tangent, may I ask, in the situation where I have an msbuild task compiled against 15.1 and I know that msbuild environments in the wild might be on 15.1, or 15.3 or 15.6, I need to test that my msbuild task works in all those msbuild environments. In this case would `MSBuildLocator` be a capable strategy - for example, can I install `15.1`, `15.3`, and `15.6` alongside each other on a single machine and then use MSBuildLocator at test time to use the specific version required for the test?

**Comment by jeffkl** [comment]
@dazinator if you have just a task library, you should not have to worry about testing against all versions.  MSBuild's assembly version is always `15.1` so your references will be that and you'll get whatever versions are next to `MSBuild.exe`.  

You'll only need to use MSBuildLocator if you want to programatically evaluate or build projects outside of MSBuild.exe.  This is common in unit tests or a custom program that does stuff with projects.

**Comment by dazinator** [comment]
@jeffkl Ok thanks. I would prefer to have test coverage of my task running in various different msbuild environments but I suppose I can consider dropping that idea if MSBuild "swears" to maintain compatibility with 15.1 :-)

I'll switch to MSBuildLocator for my tests and update my references in my test project to 15.6. Thanks again.

**Comment by jeffkl** [comment]
We try very hard to not break back compat especially for tasks.  If we do, please open an issue!  Unfortunately, doing programmatic evaluations and builds is just more complex because you need to load `Microsoft.Build.dll` in order to find MSBuild and we don't put our assemblies in the GAC anymore.   This is because you can have numerous instances of Visual Studio installed side-by-side.  So programmatic evaluations need to load `Microsoft.Build.dll` from the appropriate installed location rather than their own.  

But again, task assemblies are loaded by MSBuild itself and do not have to worry about it.  Even if we shipped MSBuild 16.0, we have assembly binding redirects in our app.config so your task compiled against 15.1 would still work, unless of course there was a breaking change, which again we try very hard not to do.

**Comment by davkean** [comment]
Going to reopen this

**Comment by davkean** [comment]
Also hit here: https://github.com/dotnet/docfx/issues/2491
