### ISSUE TITLE
Test discovery throws on *nix

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#3102]
This might be a corefx bug but I've only seen it here at the moment.

### Steps to reproduce

Run MSBuild tests on Linux or macOS without filtering away stdout.

### Expected  behavior

No mysterious stack traces

### Actual behavior

See for example https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Ubuntu16.04_CoreCLR_prtest/243/artifact/artifacts/2Debug/TestResults/Microsoft.Build.Engine.UnitTests_netcoreapp2.0_x64.log

```
[37m  Discovering: Microsoft.Build.Engine.UnitTests (method display = ClassAndMethod)
[m[33;1m   Microsoft.Build.Engine.UnitTests: Exception during discovery:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.set_Item(Int32 index, T value)
   at System.Reflection.PseudoCustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Int32& count)
   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeMethodInfo target)
   at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(MethodInfo method, Type attributeType, AttributeUsageAttribute attributeUsage) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs:line 93
   at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(String assemblyQualifiedAttributeTypeName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs:line 80
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 84
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 132
   at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 156
[m[37m  Discovered:  Microsoft.Build.Engine.UnitTests (running 1895 of 1979 test cases)
[m[37m  Starting:    Microsoft.Build.Engine.UnitTests (parallel test collections = off, max threads = 1)
```

**Comment by rainersigwald** [comment]
Not just *nix, seeing this on Windows/core for Microsoft.Build.Engine.UnitTests too.

**Comment by YuliiaKovalova** [comment]
Close as a stale issue.
We will create a new one if it happens again.
