### ISSUE TITLE
The "PropertyGroup" property is reserved

### ISSUE THREAD

**Issue by dazinator** [Microsoft/msbuild#3133]
### Steps to reproduce

When I try to restore a project with a custom SDK I see the following error:

> Microsoft.Build.Exceptions.InvalidProjectFileException : The "PropertyGroup" property is reserved, and cannot be modified.  C:\Users\Administrator\.nuget\packages\dnnvs.sdk\0.0.1-alpha0001\Sdk\Sdk.props

The `sdk.props` file looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ProjectSystemBase>$(MSBuildThisFileDirectory)..\</ProjectSystemBase>

    <PropertyGroup>
      <RulesFolderPath>$(ProjectSystemBase)Rules</RulesFolderPath>
    </PropertyGroup>
    
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <DebuggerFlavor>DnnWebsiteDebugger</DebuggerFlavor>      

    <LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
    <ResolveNuGetPackages>true</ResolveNuGetPackages>
    <DnnToolsPackageVersion Condition="'$(DnnToolsPackageVersion)'==''">0.0.2-alpha0010</DnnToolsPackageVersion> 
  
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'" Label="Configuration">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'" Label="Configuration">
    <Optimize>true</Optimize>
  </PropertyGroup>
  
</Project>

```

I can't see any of those properties listed as reserved properties here: https://msdn.microsoft.com/en-us/library/ms164309.aspx

What am I doing wrong?

### Expected  behavior

Expecting my project to restore.

### Actual behavior

> Microsoft.Build.Exceptions.InvalidProjectFileException : The "PropertyGroup" property is reserved, and cannot be modified.  C:\Users\Administrator\.nuget\packages\dnnvs.sdk\0.0.1-alpha0001\Sdk\Sdk.props

Stack:

> Result StackTrace:	
at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0)
   at Microsoft.Build.Construction.ProjectParser.ParseProjectPropertyElement(XmlElementWithLocation element, ProjectPropertyGroupElement parent)
   at Microsoft.Build.Construction.ProjectParser.ParseProjectPropertyGroupElement(XmlElementWithLocation element, ProjectElementContainer parent)
   at Microsoft.Build.Construction.ProjectParser.ParseProjectRootElementChildren(XmlElementWithLocation element)
   at Microsoft.Build.Construction.ProjectParser.Parse()
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCache projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectRootElementCache projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.<>c__DisplayClass200_0.<OpenProjectOrSolution>b__0(String path, ProjectRootElementCache cache)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.OpenProjectOrSolution(String fullPath, IDictionary`2 globalProperties, String toolsVersion, ProjectRootElementCache projectRootElementCache, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Evaluator`4.<>c__DisplayClass73_1.<ExpandAndLoadImportsFromUnescapedImportExpression>b__0(String p, ProjectRootElementCache c)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName)
   at DnnVsProjectSystem.BuildTools.Tests.MsBuildHelper.Restore(String fileName, Boolean noCache, Boolean ignorefailedsources, String packageSource, String nugetConfig) in E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\Util\MsBuildHelper.cs:line 64
   at DnnVsProjectSystem.BuildTools.Tests.ManifestBuildTests.BuildTestProject(String projectFileName, Boolean assertIsSuccess, Action`1 onBeforeBuild, String& consoleOutput) in E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\ManifestBuildTests.cs:line 244
   at DnnVsProjectSystem.BuildTools.Tests.ManifestBuildTests.WhenProjectIsBuilt(String projectName, Boolean assertSuccess, Action`1 assert) in E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\ManifestBuildTests.cs:line 163
   at DnnVsProjectSystem.BuildTools.Tests.ManifestBuildTests.Adds_Target_Assembly_To_Manifest() in E:\Repos\DnnVsProjectSystem\src\DnnVsProjectSystem.BuildTools.Tests\ManifestBuildTests.cs:line 105
Result Message:	Microsoft.Build.Exceptions.InvalidProjectFileException : The "PropertyGroup" property is reserved, and cannot be modified.  C:\Users\Administrator\.nuget\packages\dnnvs.sdk\0.0.1-alpha0001\Sdk\Sdk.props

### Environment data
`msbuild /version` output:

I am using the following msbuild nuget packages in order to restore a proj file at test time.

```
   <PackageReference Include="Microsoft.Build.Utilities.Core" Version="15.6.82" />
    <PackageReference Include="Microsoft.Build.Framework" Version="15.6.82" />
    <PackageReference Include="Microsoft.Build" Version="15.6.82" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="15.6.82" />  

```

And setting the following environment variables before calling msbuild libraries at test time:

```
        private static string VSINSTALLDIR = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community";
        private static string VisualStudioVersion = "15.0";
        private static string MSBuildSDKsPath = @"C:\Program Files\dotnet\sdk\2.1.103\Sdks\";

```

OS info:

Windows 10, dotnet --version 2.1.103

**Comment by dazinator** [comment]
Ah think I have just seen the error of my ways.. doh!

**Comment by rainersigwald** [comment]
That should definitely be documented!

(I'm assuming the problem was the nested `<PropertyGroup>`, right?)

**Comment by dazinator** [comment]
@rainersigwald yes it was the (accidental) nested property group :-)
