### ISSUE TITLE
LoadProject API throws InvalidProjectFileException on .NET 2.1 preview project

### ISSUE THREAD

**Issue by bobuva** [Microsoft/msbuild#3156]
### Steps to reproduce
1. Install the .NET Core 2.1 preview
2. Create a .NET Core console app using `dotnet new console` . No need to change the template code.
3. In a separate .NET Core console app (doesn't matter if it is .NET Core 2.0 or 2.1), use the MSBuild API to load the other project.

Results in this exception:

```
Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  c:\src\ShiftleftSecurity\sl-microagent-dotnet\ProjectAnalysis\testconsole\testconsole.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) in E:\A\_work\82\s\src\Shared\ProjectErrorUtilities.cs:line 440
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError) in E:\A\_work\82\s\src\Build\Evaluation\Evaluator.cs:line 2532
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\82\s\src\Build\Evaluation\Evaluator.cs:line 2303
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\82\s\src\Build\Evaluation\Evaluator.cs:line 2148
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in E:\A\_work\82\s\src\Build\Evaluation\Evaluator.cs:line 1066
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) in E:\A\_work\82\s\src\Build\Evaluation\Evaluator.cs:line 819
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in E:\A\_work\82\s\src\Build\Definition\Project.cs:line 2644
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in E:\A\_work\82\s\src\Build\Definition\Project.cs:line 2635
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings) in E:\A\_work\82\s\src\Build\Definition\Project.cs:line 2714
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings) in E:\A\_work\82\s\src\Build\Definition\Project.cs:line 513
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion) in E:\A\_work\82\s\src\Build\Definition\ProjectCollection.cs:line 1118
   at ProjectAnalyzer.Program.processProjectWithMsBuildApi(String projectFilename) in C:\src\ShiftLeftSecurity\sl-microagent-dotnet\ProjectAnalysis\ProjectAnalyzer\Program.cs:line 44
   at ProjectAnalyzer.Program.processDirectories(String path) in C:\src\ShiftLeftSecurity\sl-microagent-dotnet\ProjectAnalysis\ProjectAnalyzer\Program.cs:line 29
   at ProjectAnalyzer.Program.Main(String[] args) in C:\src\ShiftLeftSecurity\sl-microagent-dotnet\ProjectAnalysis\ProjectAnalyzer\Program.cs:line 18
```

Here is my program that uses the MSBuild API: Note that I pass the path to where the new console app was created as an argument:

```
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.Build.Evaluation;

namespace ProjectAnalyzer
{
    class Program
    {
        static void Main(string[] args)
        {
            //Find project(s) from the command line argument
            foreach (var path in args)
            {
                processDirectories(path);
            }
        }

        private static void processDirectories(string path)
        {
            string[] files = Directory.GetFiles(path);
            foreach (var filename in files)
            {
                if (filename.EndsWith(".csproj"))
                    processProjectWithMsBuildApi(filename);
            }

            string[] directories = Directory.GetDirectories(path);
            foreach (var dir in directories)
                processDirectories(dir);
        }

        private static void processProjectWithMsBuildApi(string projectFilename)
        {
            ProjectCollection projects = new ProjectCollection();
            Project project = projects.LoadProject(projectFilename);
            if (project == null)
            {
                Console.WriteLine("No project loaded.");
                return;
            }

            Console.WriteLine("PROJECT: {0}", project.ToString());
        }
    }
}
```

### Expected  behavior
The project is loaded by the LoadProject API and the project object is then printed to the console output.

### Actual behavior
InvalidProjectFileException occurs. See above.

### Environment data
`msbuild /version` output:
15.6.82.30579

OS info:
Windows 10 Pro
Version: 10.0.16299

dotnet --list-sdks returns:
2.1.100 [C:\Program Files\dotnet\sdk]
2.1.101 [C:\Program Files\dotnet\sdk]
2.1.2 [C:\Program Files\dotnet\sdk]
2.1.200-preview-007474 [C:\Program Files\dotnet\sdk]
2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
2.1.4 [C:\Program Files\dotnet\sdk]

**Comment by p-kaczynski** [comment]
I have the same issue. Interestingly, the same code works fine when ran as a .NET Framework 4.7.2, yet fails as .netcore

I've tried variety of things suggested elsewhere, but nothing seems to help. On both machines I've tried it I have both VS17 Enterprise and MSBuild17 installed with .NET Framework and .NET Core workloads, newest SDKs for both .NET (4.7.2) and Core (up to 2.1.300-preview1)

**Comment by Sigvaard** [comment]
It's not the only issue. After fixing this by following comments here https://github.com/Microsoft/msbuild/issues/2532 you'll get StackOverflowException... I spent all day trying to get it to work. I think MSBuild API on .NET Core is just broken...
