### ISSUE TITLE
Dotnet core stream resources does not work when built using dotnet, but works using msbuild 

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#3310]
_From @amrmahdi on May 10, 2018 7:47_

A project with embedded stream resources works fine when built using msbuild. But if build using dotnet build, it produces the following exception 

```console
Unhandled Exception: System.InvalidOperationException: Resource 'Silence' was not a Stream - call GetObject instead.
   at System.Resources.ResourceManager.GetStream(String name, CultureInfo culture)
   at dotnetcore.resources.Program.Main(String[] args) in E:\dotnetcore.resources\Program.cs:line 13
```

### MSBuild (works)
1. msbuild
2. dotnet run

### dotnet (does not work)
1. dotnet run

### dotnet version
2.1.300-preview2-00853

I've noticed that when using MSBuild, **Al.exe** is used to generate the satellite assemblies, which maybe why it works when building using MSBuild.

[dotnet.resources.zip](https://github.com/dotnet/sdk/files/1990751/dotnet.resources.zip)

_Copied from original issue: dotnet/sdk#2231_

**Comment by nguerrera** [comment]
Duplicate of https://github.com/Microsoft/msbuild/issues/2221

**Comment by nguerrera** [comment]
> I've noticed that when using MSBuild, Al.exe is used to generate the satellite assemblies, which maybe why it works when building using MSBuild.

This isn't related. The problem is at the point where the .resources file is generated. AL.exe (on desktop msbuild) or csc.exe (on core msbuld) will put the .resources into a satellite equivalently, but they'll be equally wrong if the .resources file is wrong.
