### ISSUE TITLE
NullReferenceException in BuildEnvironmentHelper when creating instance of BuildParameters or ProjectCollection

### ISSUE THREAD

**Issue by zcanann** [Microsoft/msbuild#3372]
`ProjectCollection projectCollection = new ProjectCollection();`

```
Exception thrown: 'System.NullReferenceException' in Microsoft.Build.dll

   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance() in /_/src/Shared/BuildEnvironmentHelper.cs:line 59
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsMono() in /_/src/Shared/NativeMethodsShared.cs:line 525
   at Microsoft.Build.BackEnd.Logging.LoggingService..ctor(LoggerMode loggerMode, Int32 nodeId) in /_/src/Build/BackEnd/Components/Logging/LoggingService.cs:line 226
   at Microsoft.Build.Evaluation.ProjectCollection.CreateLoggingService(Int32 maxCPUCount, Boolean onlyLogCriticalEvents) in /_/src/Build/Definition/ProjectCollection.cs:line 1692
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents) in /_/src/Build/Definition/ProjectCollection.cs:line 353
   at Microsoft.Build.Evaluation.ProjectCollection..ctor() in /_/src/Build/Definition/ProjectCollection.cs:line 252
```

`BuildParameters buildParameters = new BuildParameters();`

```
Exception thrown: 'System.NullReferenceException' in Microsoft.Build.dll

   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance() in /_/src/Shared/BuildEnvironmentHelper.cs:line 59
   at Microsoft.Build.Execution.BuildParameters.FindMSBuildExe() in /_/src/Build/BackEnd/BuildManager/BuildParameters.cs:line 1054
   at Microsoft.Build.Execution.BuildParameters.Initialize(PropertyDictionary`1 environmentProperties, ProjectRootElementCache projectRootElementCache, ToolsetProvider toolsetProvider) in /_/src/Build/BackEnd/BuildManager/BuildParameters.cs:line 1021
```

Just a simple example of pulling the latest Microsoft.Build NuGet packages from a .net standard 2.0 project and attempting to initialize these objects.

List of included NuGet packages:
Microsoft.Build
Microsoft.Build.Framework
Microsoft.Build.Runtime
Microsoft.Build.Tasks.Core
Microsoft.Build.Utilities.Core

What am I missing here?

**Comment by duskembayev** [comment]
I have a similar issue, but another exception type:
```
System.Reflection.TargetException: Non-static method requires a target.
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsMono()
   at Microsoft.Build.BackEnd.Logging.LoggingService..ctor(LoggerMode loggerMode, Int32 nodeId)
   at Microsoft.Build.BackEnd.Logging.LoggingService.CreateLoggingService(LoggerMode mode, Int32 node)
   at Microsoft.Build.Evaluation.ProjectCollection.CreateLoggingService(Int32 maxCPUCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, ToolsetDefinitionLocations toolsetDefinitionLocations)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties)
```
