### ISSUE TITLE
 error MSB4018: The "GenerateResource" task failed unexpectedly

### ISSUE THREAD

**Issue by twenzel** [Microsoft/msbuild#364]
After uninstall Visual Studio 2015 Update 1 RC and reinstall VS 2015 RTM I can't compile any of my projects any more. Following error occurs:
```
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB4018: The "GenerateResource" task failed unexpectedly.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB4018:    at Microsoft.Build.Tasks.ResGenDependencies.GetResXFileInfo(String resxFile)
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB4018:    at Microsoft.Build.Tasks.GenerateResource.ShouldRebuildResgenOutputFile(String sourceFilePath, String outputFilePath)
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB4018:    at Microsoft.Build.Tasks.GenerateResource.GetResourcesToProcess(List`1& inputsToProcess, List`1& outputsToProcess, List`1& cachedOutputFiles)
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB4018:    at Microsoft.Build.Tasks.GenerateResource.Execute()
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

```

**Comment by twenzel** [comment]
The same problem occurs also when I try to build a solution with MSBuild command line (on a clean machine) when only Build Tools 2015, .NET developer pack and .NET SDK are installed.

**Comment by rainersigwald** [comment]
That callstack is the problem that was fixed with #314, but I'm confused by your second statement--that should only cause problems on machines that had MSBuild Update 1 installed and then uninstalled.  Is your Build Tools-only machine in that state?  If not, I'll want to dig in further.

To work around #314, completely delete all build outputs and build again--the issue is that an internal cache gets interpreted incorrectly on the old bits, causing this crash.

**Comment by twenzel** [comment]
Your solution fixed my problem (on both machines). Thanks!

**Comment by dby** [comment]
Your solution also fixed my problem, thank you very much

**Comment by SzymonSasin** [comment]
When Visula Studio Team Service will recieve this fix?
