### ISSUE TITLE
ProjectCollection throws InvalidCastException on .NET Core 3.0

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#3834]
### Steps to reproduce

Discovered while updating ASP.NET to build with the .NET Core 3.0 SDK nightlies: https://github.com/aspnet/BuildTools/pull/786.

To reproduce, clone the branch for this PR and run "build.cmd/sh" on any platform.

### Expected  behavior

I can use the `Microsoft.Build.Evaluation.ProjectCollection` API on .NET Core 3.0.

### Actual behavior
```
Unable to cast object of type 'System.Linq.EmptyPartition`1[Microsoft.Build.Evaluation.Project]' to type 'System.Collections.Generic.IList`1[Microsoft.Build.Evaluation.Project]'.
   at Microsoft.Build.Evaluation.ProjectCollection.LoadedProjectCollection.GetMatchingProjectsIfAny(String fullPath) in /_/src/Build/Definition/ProjectCollection.cs:line 2334
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(String fullPath) in /_/src/Build/Definition/ProjectCollection.cs:line 986
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.GetProject(String path, ProjectCollection projectCollection, Boolean policyDesignBuild) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 109
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.Create(String path, Boolean policyDesignBuild) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 70
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.<>c__DisplayClass2_0.<CreateMany>b__2(String projectFile) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 54
```

### Environment data
msbuild -version:
```
Microsoft (R) Build Engine version 15.9.8-preview+g0a5001fc4d for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.8.20490
```
OS info: any
dotnet cli: 3.0.100-alpha1-009638

**Comment by natemcmaster** [comment]
Caused by changes in .NET Core (https://github.com/dotnet/corefx/pull/31025) and this line of code:

https://github.com/Microsoft/msbuild/blob/f9fdb72a70b76c18d7eca38fd95e3164ae21acae/src/Build/Definition/ProjectCollection.cs#L2353
