### ISSUE TITLE
Microsoft.Build conflicting with NuGet.ProjectModel

### ISSUE THREAD

**Issue by Sigvaard** [Microsoft/msbuild#3921]
I'm trying to use MSBuild programmatically in .NET Core 2.1 console app, everything works fine so far after solving a couple of problems, but there's some weird error when I reference NuGet.ProjectModel:

```
  Task "ResolvePublishAssemblies"
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018: The "ResolvePublishAssemblies" task failed unexpectedly.
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'NuGet.ProjectModel, Version=4.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018: File name: 'NuGet.ProjectModel, Version=4.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePublishAssemblies.ExecuteCore()
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in /_/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:line 580
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) in /_/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:line 784
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018:
    C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(280,5): error MSB4018:
```

It happens when building some project.

My .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Microsoft.Build" Version="15.8.166" />
    <PackageReference Include="Microsoft.Build.Framework" Version="15.8.166" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="15.8.166" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="15.8.166" />
    <PackageReference Include="NuGet.ProjectModel" Version="4.8.0" />
  </ItemGroup>

</Project>

```

`<PackageReference Include="NuGet.ProjectModel" Version="4.8.0" />` is causing the problem for some reason and build fails when I reference it

thanks in advance.

**Comment by Sigvaard** [comment]
Unfortunately `<PackageReference Include="NuGet.ProjectModel" Version="4.8.0-rtm.5362" />` didn't solve the problem.

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.
