### ISSUE TITLE
InvalidOperationException in ProfilerLogger

### ISSUE THREAD

**Issue by xoofx** [Microsoft/msbuild#3967]
Hey, I'm using the following code to compile a same project in a loop from a console and generate binary+profile logs:

```C#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using Microsoft.Build.Evaluation;
using Microsoft.Build.Execution;
using Microsoft.Build.Framework;
using Microsoft.Build.Logging;
using Microsoft.Build.Utilities;

namespace BuildServer
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length != 1)
            {
                Console.WriteLine("Error: expecting a csproj");
                Console.WriteLine($"Usage: {Path.GetFileName(Assembly.GetExecutingAssembly().Location)}  a_msbuild.csproj");
                Environment.Exit(1);
            }

            var projectFile = args[0];
            var sdkPath = @"C:\Program Files\dotnet\sdk\2.1.402";

            Environment.SetEnvironmentVariable("MSBuildExtensionsPath", sdkPath);
            Environment.SetEnvironmentVariable("MSBuildSDKsPath", $@"{sdkPath}\Sdks\");

            var clock = Stopwatch.StartNew();
            while (true)
            {
                clock.Restart();

                var globalProperties = new Dictionary<string, string>
                {
                    ["MSBuildExtensionsPath"] = sdkPath,
                    ["MSBuildSDKsPath"] = $@"{sdkPath}\Sdks",
                    ["RoslynTargetsPath"] = $@"{sdkPath}\Roslyn",
                    ["DisableHandlePackageFileConflicts"] = "true",
                    ["IgnoreDefaultInstalledAssemblyTables"] = "true",
                    ["IgnoreInstalledAssemblySubsetTables"] = "true"
                };

                using (ProjectCollection projectCollection = new ProjectCollection(globalProperties, new List<ILogger>(), ToolsetDefinitionLocations.Default))
                {
                    projectCollection.AddToolset(new Toolset(ToolLocationHelper.CurrentToolsVersion, sdkPath, projectCollection, string.Empty));
                    projectCollection.LoadProject(projectFile);

                    var defaultBuildManager = BuildManager.DefaultBuildManager;
                    var buildRequestData = new BuildRequestData(projectFile, globalProperties, projectCollection.DefaultToolsVersion, new[] { "Build" }, null);

                    var loggers = new List<ILogger>
                    {
                        new ConsoleLogger(LoggerVerbosity.Quiet),
                        new BinaryLogger {Parameters = "msbuild.binlog"},
                        new ProfilerLogger("profile.log")
                    };
                    var buildParameters = new BuildParameters(projectCollection) {DetailedSummary = true, Loggers = loggers};


                    defaultBuildManager.BeginBuild(buildParameters);
                    try
                    {
                        var build = defaultBuildManager.PendBuildRequest(buildRequestData);
                        build.Execute();
                    }
                    finally
                    {
                        defaultBuildManager.EndBuild();
                    }
                }

                Console.WriteLine($"Running in: {clock.Elapsed.TotalMilliseconds}ms");
                Console.WriteLine("Press [enter] to launch it again");
                Console.ReadLine();
            }
        }
    }
}
```
But when using a ProfilerLogger, on the second loop (while nothing changed), I'm getting the following exception:

```
Writing profiler report to 'profile.log'...

Unhandled Exception: Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because the "ProfilerLogger" logger failed unexpectedly during shutdown. ---> System.InvalidOperationException: Nullable object must have a value.
   at Microsoft.Build.Logging.ProfilerLogger.FindBigEnoughParentId(IDictionary`2 idTable, Nullable`1 parentId) in /_/src/Build/Logging/ProfilerLogger.cs:line 240
   at Microsoft.Build.Logging.ProfilerLogger.PruneSmallItems(IDictionary`2 aggregatedLocations) in /_/src/Build/Logging/ProfilerLogger.cs:line 227
   at Microsoft.Build.Logging.ProfilerLogger.GetAggregatedResult(Boolean pruneSmallItems) in /_/src/Build/Logging/ProfilerLogger.cs:line 153
   at Microsoft.Build.Logging.ProfilerLogger.GenerateProfilerReport() in /_/src/Build/Logging/ProfilerLogger.cs:line 289
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger) in /_/src/Build/BackEnd/Components/Logging/LoggingService.cs:line 1203
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs) in /_/src/Build/Errors/InternalLoggerException.cs:line 234
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger) in /_/src/Build/BackEnd/Components/Logging/LoggingService.cs:line 1212
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent() in /_/src/Build/BackEnd/Components/Logging/LoggingService.cs:line 739
   at Microsoft.Build.BackEnd.BuildComponentFactoryCollection.BuildComponentEntry.ShutdownSingletonInstance() in /_/src/Build/BackEnd/Components/BuildComponentFactoryCollection.cs:line 229
   at Microsoft.Build.Execution.BuildManager.ShutdownLoggingService(ILoggingService loggingService) in /_/src/Build/BackEnd/BuildManager/BuildManager.cs:line 1871
   at Microsoft.Build.Execution.BuildManager.EndBuild() in /_/src/Build/BackEnd/BuildManager/BuildManager.cs:line 635
   at BuildServer.Program.Main(String[] args) in C:\Work\tmp\BuildServer\BuildServer\Program.cs:line 66
```

Any ideas from what could that come?

**Comment by xoofx** [comment]
I build a debug version and I'm getting this error on the following case:

![image](https://user-images.githubusercontent.com/715038/49218957-212bcb00-f3d2-11e8-944a-7ad78c2ac5af.png)

It's seems that it's the "total evaluation", which is going through this loop because it is `IsTooSmall(pair.Value)` while `pair.Key.IsEvaluationPass=true` 

I don't know why on a first pass we don't get this total evaluation while on a second we do.

Do you have any idea why it's happening?

**Comment by xoofx** [comment]
Ok, so it happens because on the first run, the total evaluation is enough big, but on a second pass, things are running more quickly, so the loop is crashing while trying to access the parentId of this total evaluation.

I have replaced the code with the following which imo is more adequate:

```
            // We go up the parent relationship until we find an item that is either an evaluation pass or a big enough regular item
            while (pair.Key.ParentId.HasValue && (!pair.Key.IsEvaluationPass || IsTooSmall(pair.Value)))
            {
                pair = idTable[pair.Key.ParentId.Value];
            }
```

Do you think that's fine? If yes, I will make a PR

**Comment by rainersigwald** [comment]
@smera ☝?

**Comment by smera** [comment]
Let me take a more careful look. The proposed change will for sure prevent the crash, but it might be hiding the real problem. The invariant should be that all evaluation locations that don't represent a pass should have a parent. Ignoring the lack of parent may result in a whole branch of profiled locations to be skipped completely when the report is generated.

**Comment by smera** [comment]
Ok, I think I know what's going on. The location in question *is* an evaluation pass (looking at the screenshot @xoofx sent, the location is the total evaluation pass). So it does not have a parent by definition. The problem is that the evaluation pass is also small enough. I think in those cases the only option is to include it as is. So I think the change should be to do:

`while (!pair.Key.IsEvaluationPass && IsTooSmall(pair.Value))`

**Comment by xoofx** [comment]
Great @smera I will open a PR with that fix! 👍
