### ISSUE TITLE
InnerBuildsCanHaveSeparateReferences is flaky

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#4266]
On running `Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences` repeatedly, it fails about 20% of the time on my machine:

```
S:\msbuild>for /L %I in (1,1,5) do "S:\msbuild\.dotnet\dotnet.exe" exec --depsfile "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.deps.json" --runtimeconfig "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.runtimeconfig.json"  "C:\Users\raines\.nuget\packages\xunit.runner.console/2.4.1-pre.build.4059/tools/netcoreapp2.0/xunit.console.dll" "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.dll" -method Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences

S:\msbuild>"S:\msbuild\.dotnet\dotnet.exe" exec --depsfile "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.deps.json" --runtimeconfig "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.runtimeconfig.json"  "C:\Users\raines\.nuget\packages\xunit.runner.console/2.4.1-pre.build.4059/tools/netcoreapp2.0/xunit.console.dll" "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.dll" -method Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27414.06)
  Discovering: Microsoft.Build.Engine.UnitTests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Build.Engine.UnitTests (found 1 of 2158 test case)
  Starting:    Microsoft.Build.Engine.UnitTests (parallel test collections = off, max threads = 1)
  Finished:    Microsoft.Build.Engine.UnitTests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Build.Engine.UnitTests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.689s

S:\msbuild>"S:\msbuild\.dotnet\dotnet.exe" exec --depsfile "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.deps.json" --runtimeconfig "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.runtimeconfig.json"  "C:\Users\raines\.nuget\packages\xunit.runner.console/2.4.1-pre.build.4059/tools/netcoreapp2.0/xunit.console.dll" "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.dll" -method Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27414.06)
  Discovering: Microsoft.Build.Engine.UnitTests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Build.Engine.UnitTests (found 1 of 2158 test case)
  Starting:    Microsoft.Build.Engine.UnitTests (parallel test collections = off, max threads = 1)
  Finished:    Microsoft.Build.Engine.UnitTests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Build.Engine.UnitTests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.712s

S:\msbuild>"S:\msbuild\.dotnet\dotnet.exe" exec --depsfile "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.deps.json" --runtimeconfig "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.runtimeconfig.json"  "C:\Users\raines\.nuget\packages\xunit.runner.console/2.4.1-pre.build.4059/tools/netcoreapp2.0/xunit.console.dll" "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.dll" -method Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27414.06)
  Discovering: Microsoft.Build.Engine.UnitTests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Build.Engine.UnitTests (found 1 of 2158 test case)
  Starting:    Microsoft.Build.Engine.UnitTests (parallel test collections = off, max threads = 1)
  Finished:    Microsoft.Build.Engine.UnitTests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Build.Engine.UnitTests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.701s

S:\msbuild>"S:\msbuild\.dotnet\dotnet.exe" exec --depsfile "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.deps.json" --runtimeconfig "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.runtimeconfig.json"  "C:\Users\raines\.nuget\packages\xunit.runner.console/2.4.1-pre.build.4059/tools/netcoreapp2.0/xunit.console.dll" "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.dll" -method Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27414.06)
  Discovering: Microsoft.Build.Engine.UnitTests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Build.Engine.UnitTests (found 1 of 2158 test case)
  Starting:    Microsoft.Build.Engine.UnitTests (parallel test collections = off, max threads = 1)
Failure: node Microsoft.Build.Experimental.Graph.ProjectGraphNode has properties [IsGraphBuild, true]
    Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences [FAIL]
      System.Collections.Generic.KeyNotFoundException : The given key 'InnerBuild' was not present in the dictionary.
      Stack Trace:
           at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
           at System.Collections.ObjectModel.ReadOnlyDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.get_Item(TKey key)
        S:\msbuild\src\Build.UnitTests\Graph\ProjectGraph_Tests.cs(1392,0): at Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.<>c.<InnerBuildsCanHaveSeparateReferences>b__57_0(ProjectGraphNode n)
           at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
           at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
        S:\msbuild\src\Build.UnitTests\Graph\ProjectGraph_Tests.cs(1388,0): at Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences()
  Finished:    Microsoft.Build.Engine.UnitTests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Build.Engine.UnitTests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.801s

S:\msbuild>"S:\msbuild\.dotnet\dotnet.exe" exec --depsfile "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.deps.json" --runtimeconfig "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.runtimeconfig.json"  "C:\Users\raines\.nuget\packages\xunit.runner.console/2.4.1-pre.build.4059/tools/netcoreapp2.0/xunit.console.dll" "S:\msbuild\artifacts\bin\Microsoft.Build.Engine.UnitTests\Debug\netcoreapp2.1\Microsoft.Build.Engine.UnitTests.dll" -method Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.InnerBuildsCanHaveSeparateReferences
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27414.06)
  Discovering: Microsoft.Build.Engine.UnitTests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Build.Engine.UnitTests (found 1 of 2158 test case)
  Starting:    Microsoft.Build.Engine.UnitTests (parallel test collections = off, max threads = 1)
  Finished:    Microsoft.Build.Engine.UnitTests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Build.Engine.UnitTests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.668s
```

That output is with this patch:

```diff
diff --git a/src/Build.UnitTests/Graph/ProjectGraph_Tests.cs b/src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
index df0d7d7c3..f44d80e77 100644
--- a/src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
+++ b/src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
@@ -1385,7 +1385,18 @@ namespace Microsoft.Build.Experimental.Graph.UnitTests
             AssertNonMultitargetingNode(GetFirstNodeWithProjectNumber(graph, 3));
             AssertNonMultitargetingNode(GetFirstNodeWithProjectNumber(graph, 5));
 
-            var innerBuildWithCommonReferences = GetNodesWithProjectNumber(graph, 1).First(n => n.ProjectInstance.GlobalProperties[InnerBuildPropertyName] == "a");
+            var innerBuildWithCommonReferences = GetNodesWithProjectNumber(graph, 1).First(n =>
+            {
+                try
+                {
+                    return n.ProjectInstance.GlobalProperties[InnerBuildPropertyName] == "a";
+                }
+                catch (System.Collections.Generic.KeyNotFoundException)
+                {
+                    Console.WriteLine($"Failure: node {n} has properties {string.Join(";", n.ProjectInstance.GlobalProperties)}");
+                    throw;
+                }
+            });
 
             innerBuildWithCommonReferences.ProjectReferences.Count.ShouldBe(4);
             var referenceNumbersSet = innerBuildWithCommonReferences.ProjectReferences.Select(r => Path.GetFileNameWithoutExtension(r.ProjectInstance.FullPath)).ToHashSet();
```

so there's a tiny bit more information than the bare failure.

**Comment by cdmihai** [comment]
Fixed in #4310
