### ISSUE TITLE
System.MissingMethodException in MSBuild bundled with VS2019

### ISSUE THREAD

**Issue by Hubert-Rybak** [Microsoft/msbuild#4286]
On fresh installation of VS2019, when trying to build project from VS Console, I'm getting following error on every solution:

```csharp
System.MissingMethodException: Method not found: 'Void Microsoft.Build.Evaluation.ProjectCollection..ctor(System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IEnumerable`1<Microsoft.Build.Framework.ILogger>, System.Collections.Generic.IEnumerable`1<Microsoft.Build.Logging.ForwardingLoggerRecord>, Microsoft.Build.Evaluation.ToolsetDefinitionLocations, Int32, Boolean, Boolean)'.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: System.MissingMethodException: Method not found: 'Void Microsoft.Build.Evaluation.ProjectCollection..ctor(System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IEnumerable`1<Microsoft.Build.Framework.ILogger>, System.Collections.Generic.IEnumerable`1<Microsoft.Build.Logging.ForwardingLoggerRecord>, Microsoft.Build.Evaluation.ToolsetDefinitionLocations, Int32, Boolean, Boolean)'.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```
When trying to open solution directly from VS, projects are failing to load, and MSBuild just crashes.
There is also ongoing discussion about this here: 
https://developercommunity.visualstudio.com/content/problem/500131/0-projects-in-solution-explorer-in-visual-studio-2.html

**Comment by rainersigwald** [comment]
Can you please download and run https://github.com/Microsoft/msbuild/blob/master/scripts/EnumerateMSBuild.ps1 and post the results? I suspect you have an old version of MSBuild installed in your GAC.

**Comment by Hubert-Rybak** [comment]
Output: https://gist.github.com/Hubert-Rybak/efcda923cd3c06e0b9817bc26f4d10cb

**Comment by rainersigwald** [comment]
Thank you, that shows the problem. You have MSBuild assemblies in your Global Assembly Cache, which they're not designed for.

You can run these commands from an elevated Developer Command Prompt to remove them:

```
gacutil /u "MSBuild, Version=15.1.0.0"
gacutil /u "Microsoft.Build.Conversion.Core, Version=15.1.0.0"
gacutil /u "Microsoft.Build, Version=15.1.0.0"
gacutil /u "Microsoft.Build.Engine, Version=15.1.0.0"
gacutil /u "Microsoft.Build.Tasks.Core, Version=15.1.0.0"
gacutil /u "Microsoft.Build.Utilities.Core, Version=15.1.0.0"
gacutil /u "Microsoft.Build.Framework, Version=15.1.0.0"
```

After that, VS 2017 and VS 2019 will be able to each have their own copy of MSBuild and they won't interfere with one another.

**Comment by Hubert-Rybak** [comment]
Thanks, it helped! Something must gone wrong during VS2019 install or VS2017 uninstall.

**Comment by kerrpeter** [comment]
Fresh install of VS2019 preview 5 and I had same problem.
Fix from @rainersigwald  solved it.
I'm not aware of anything I did within VS2017 to place MSBuild assemblies in your Global Assembly Cache.
Would be good if the VS2019 install automatically checked this

**Comment by rainersigwald** [comment]
> Would be good if the VS2019 install automatically checked this

I agree. Unfortunately, the current VS setup process doesn't make this easy to do. We'll sync with the Setup team again to see if our options have improved there.

**Comment by Blizzardo1** [comment]
I am using the latest Rider version (2019.3 EAP 4; At the time of this comment) and have not been able to utilize WinForms at all since I removed VS2019 for being too broken on my system months ago. Since then I have had no space to even reconsider VS2019 as the SSD I am working with is far too small (Yes I have been considering a newer SSD, one with more space... sosumi)

Currently I can only do Console Applications, nothing requiring even a spec of GUI libraries. So far, I have had no luck in using the latest version of MSBuild other than through the Dotnet SDK 2.2.202 which I assume now is not the latest version anymore, however it does not build GUIs. I had installed MSBuild separately which installed it into the VS2019 folder on my workstation, however I get the following error:    https://gist.github.com/Blizzardo1/55a73801b733d5b7a12dafc0e553a9c7

By googling it had lead me here and thus I ran the EnumerateMSBuild script which got me the following output:    https://gist.github.com/Blizzardo1/5d97e68fe7119394d696c90d73b4f8c0

Please let me know what I can do to finally fix this 6 month issue once and for all.

Thank you.
