### ISSUE TITLE
AllNodesShouldHaveGraphBuildGlobalProperty Test Failure On MacOS

### ISSUE THREAD

**Issue by BenVillalobos** [Microsoft/msbuild#4312]
This test randomly failed on macOS .NET Core 2.1. Re-running the test resulted in a success. Likely similar to #4310 

## Exception
```
System.Collections.Generic.KeyNotFoundException : The given key 'Microsoft.Build.BackEnd.ConfigurationMetadata' was not present in the dictionary.
```
## Call Stack
```
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.Build.Experimental.Graph.ProjectGraph.<CreateEdgesAndDetectCycles>g__CreateEdgesAndDetectCyclesForRoot|14_0(ProjectGraphNode node, ConfigurationMetadata nodeConfig, IDictionary`2 nodeState, <>c__DisplayClass14_0& ) in /_/src/Build/Graph/ProjectGraph.cs:line 314
   at Microsoft.Build.Experimental.Graph.ProjectGraph.<CreateEdgesAndDetectCycles>g__CreateEdgesAndDetectCyclesForRoot|14_0(ProjectGraphNode node, ConfigurationMetadata nodeConfig, IDictionary`2 nodeState, <>c__DisplayClass14_0& ) in /_/src/Build/Graph/ProjectGraph.cs:line 341
   at Microsoft.Build.Experimental.Graph.ProjectGraph.CreateEdgesAndDetectCycles(List`1 entryPointConfigurationMetadata, ProjectInterpretation sdkInfo, ConcurrentDictionary`2 allParsedProjects) in /_/src/Build/Graph/ProjectGraph.cs:line 293
   at Microsoft.Build.Experimental.Graph.ProjectGraph.LoadGraph(List`1 entryPointConfigurationMetadata, ProjectCollection projectCollection, ProjectInstanceFactoryFunc projectInstanceFactory, ProjectInterpretation sdkInfo) in /_/src/Build/Graph/ProjectGraph.cs:line 248
   at Microsoft.Build.Experimental.Graph.ProjectGraph..ctor(IEnumerable`1 entryPoints, ProjectCollection projectCollection, ProjectInstanceFactoryFunc projectInstanceFactory) in /_/src/Build/Graph/ProjectGraph.cs:line 204
   at Microsoft.Build.Experimental.Graph.ProjectGraph..ctor(IEnumerable`1 entryProjectFiles, IDictionary`2 globalProperties) in /_/src/Build/Graph/ProjectGraph.cs:line 108
   at Microsoft.Build.UnitTests.Helpers.CreateProjectGraph(TestEnvironment env, IDictionary`2 dependencyEdges, IDictionary`2 globalProperties, CreateProjectFileDelegate createProjectFile, IEnumerable`1 roots) in /Users/vsts/agent/2.149.2/work/1/s/src/Shared/UnitTests/ObjectModelHelpers.cs:line 1635
   at Microsoft.Build.Experimental.Graph.UnitTests.ProjectGraphTests.AllNodesShouldHaveGraphBuildGlobalProperty(Dictionary`2 edges, Int32[] roots, Dictionary`2 globalProperties) in /Users/vsts/agent/2.149.2/work/1/s/src/Build.UnitTests/Graph/ProjectGraph_Tests.cs:line 1610
```

**Comment by rainersigwald** [comment]
@cdmihai, can you take a look at this or route?
