### ISSUE TITLE
Ctrl-C process termination throws on Linux

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#434]
Ran a build, thought better of it. Got this:

```
^CAttempting to cancel the build...
/home/raines/src/corefx/build.proj(40,5): warning MSB5021: "sh" and its child processes are being terminated in order to cancel the build.
/home/raines/src/corefx/build.proj(40,5): warning MSB4018: The "Exec" task failed unexpectedly.
/home/raines/src/corefx/build.proj(40,5): warning MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
/home/raines/src/corefx/build.proj(40,5): warning MSB4018: System.DllNotFoundException: Unable to load DLL 'KERNEL32.DLL': The specified module could not be found.
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:  (Exception from HRESULT: 0x8007007E)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.OpenProcess(eDesiredAccess dwDesiredAccess, Boolean bInheritHandle, Int32 dwProcessId)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.KillTree(Int32 processIdToKill)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.KillToolProcessOnTimeout(Process proc, Boolean isBeingCancelled)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.TerminateToolProcess(Process proc, Boolean isBeingCancelled)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Tasks.Exec.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
```

We should at the very least not throw and probably should have a better implementation of this.

**Comment by jasonwilliams200OK** [comment]
Fixed by #886. :sunglasses:

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Leaving open until test is enabled.

**Comment by jeffkl** [comment]
Is this fixed?  I haven't hit it...

**Comment by rainersigwald** [comment]
Yup, the fix seems to be working as advertised (yay!).

**Comment by jeffkl** [comment]
I'm going to re-enable the test by reverting 2b3d4f1cd1cb50a3c942d77e316338e448385d2f and then close this if it passes.
