### ISSUE TITLE
System.Reflection.TargetException in BuildEnvironmentHelper when creating instance ProjectCollection

### ISSUE THREAD

**Issue by duskembayev** [microsoft/msbuild#4534]
### Steps to reproduce

I use .NET Core host using the hosting APIs from CoreClrHost.h.
Target managed assembly is self-contained and references to `Microsoft.Build 16.0.461`.

This code running in background thread:
`ProjectCollection projectCollection = new ProjectCollection();`

### Stacktrace:
```
System.Reflection.TargetException: Non-static method requires a target.
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsMono()
   at Microsoft.Build.BackEnd.Logging.LoggingService..ctor(LoggerMode loggerMode, Int32 nodeId)
   at Microsoft.Build.BackEnd.Logging.LoggingService.CreateLoggingService(LoggerMode mode, Int32 node)
   at Microsoft.Build.Evaluation.ProjectCollection.CreateLoggingService(Int32 maxCPUCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, ToolsetDefinitionLocations toolsetDefinitionLocations)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties)
```
### .NET Core version
3.0.0-preview6-27804-01

After investigation, I've found that exception occurs here:
`BuildEnvironmentHelper.GetProcessFromRunningProcess()`.
Reason: `AssemblyUtilities.EntryAssembly = null`.

**Comment by livarcocc** [comment]
Could you share some code with us that we could use to reproduce this and debug the code?

**Comment by duskembayev** [comment]
You can found an example here: https://github.com/duskembayev/samples/tree/msbuild_4534/core/hosting/HostWithCoreClrHost
It based on .NET Core hosting sample.
