### ISSUE TITLE
Referencing C++/WinRT static library results in MSB3272

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4547]
Originally filed as https://developercommunity.visualstudio.com/content/problem/629524/static-library-reference-causes-there-was-a-proble.html

Repro via @DHowett-MSFT: [DoStaticCppWinrtLibrariesWorkOrNot.zip](https://github.com/microsoft/msbuild/files/3432120/DoStaticCppWinrtLibrariesWorkOrNot.zip) who also developed a workaround: https://github.com/microsoft/terminal/pull/2007/commits/40beb06dde29a39549af7af0dd19ab3dc697a7e1.

```
error MSB3272: There was a problem reading the implementation file "S:\repro\devdiv\DevDiv\948240\ARM\Debug\ComponentLib\ComponentLib.lib". "Unable to read beyond the end of the stream." [S:\repro\devdiv\DevDiv\948240\ComponentDll\ComponentDll.vcxproj]
```

The full exception stack is:

```
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes) in f:\dd\ndp\clr\src\BCL\system\io\binaryreader.cs:line 580
   at System.IO.BinaryReader.ReadUInt32() in f:\dd\ndp\clr\src\BCL\system\io\binaryreader.cs:line 191
   at Microsoft.Build.Tasks.ReferenceTable.ReadMachineTypeFromPEHeader(String dllPath) in /_/src/Tasks/AssemblyDependency/ReferenceTable.cs:line 2905
   at Microsoft.Build.Tasks.ReferenceTable.VerifyArchitectureOfImplementationDll(String dllPath, String winmdFile) in /_/src/Tasks/AssemblyDependency/ReferenceTable.cs:line 2796
```

This is a regression resulting from #4418.

**Comment by rainersigwald** [comment]
If anyone is in need of a self-contained general workaround:

```xml
  <!--
    work around https://github.com/microsoft/msbuild/issues/4547
    Remove after updating to Visual Studio 16.3 preview 2 or higher.
  -->
  <Target Name="WorkAroundMSBuild4547_Remove" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <_StaticLibraryProjectReference Include="@(_ResolvedProjectReferencePaths)" Condition="'$([System.IO.Path]::GetExtension(`%(Implementation)`))' == '.lib'" />
      <_ResolvedProjectReferencePaths Remove="@(_StaticLibraryProjectReference)" />
      <_ResolvedProjectReferencePaths Include="@(_StaticLibraryProjectReference)">
        <Implementation />
      </_ResolvedProjectReferencePaths>
    </ItemGroup>
  </Target>

  <Target Name="WorkAroundMSBuild4547_Restore" AfterTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <_ResolvedProjectReferencePaths Remove="@(_StaticLibraryProjectReference)" />
      <_ResolvedProjectReferencePaths Include="@(_StaticLibraryProjectReference)" />
    </ItemGroup>
  </Target>
  <!-- End https://github.com/microsoft/msbuild/issues/4547 workaround -->
```

If you have more than one affected project, the easiest way to import it into all of them is to put that in a [`Directory.Build.targets` file](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets) (surrounded by `<Project></Project>`, if you don't have one already).
