### ISSUE TITLE
After upgrading to 16.3.0 Preview 2.0 VB Core 3.0 libraries no longer compile

### ISSUE THREAD

**Issue by paul1956** [microsoft/msbuild#4616]
### Steps to reproduce
After upgrading to 16.3.0 Preview 2.0, A Core 3.0  VB applications don't compiler anymore. I get Error BC30002 Type 'Global.Microsoft.VisualBasic.MyServices.Internal.ContextValue' is not defined.
https://github.com/paul1956/CSharpToVB

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <RootNamespace>ManageProgressBar</RootNamespace>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="4.5.1" />
  </ItemGroup>
</Project>
```
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace></RootNamespace>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
    <OptionInfer>Off</OptionInfer>
    <AssemblyName>VB.CodeConverter</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>16</LangVersion>
    <OptionExplicit>On</OptionExplicit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.2.1" />
    <PackageReference Include="VBMsgBox" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HashLibrary\HashLibrary.csproj" />
    <ProjectReference Include="..\ManageProgressBar\ManageProgressBar.vbproj" />
  </ItemGroup>
</Project>
```
    Also
```
    Error    MSB4018    The "GenerateResource" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Tasks.ProcessResourceFiles.get_HaveSystemResourcesExtensionsReference()
   at Microsoft.Build.Tasks.ProcessResourceFiles.WriteBinaryResources(ReaderInfo reader, String filename)
   at Microsoft.Build.Tasks.ProcessResourceFiles.WriteResources(ReaderInfo reader, String filename)
   at Microsoft.Build.Tasks.ProcessResourceFiles.ProcessFile(String inFile, String outFileOrDir)
   at Microsoft.Build.Tasks.ProcessResourceFiles.Run(TaskLoggingHelper log, ITaskItem[] assemblyFilesList, List`1 inputs, List`1 satelliteInputs, List`1 outputs, Boolean sourcePath, Boolean usePreserializedResources, String language, String namespacename, String resourcesNamespace, String filename, String classname, Boolean publicClass, Boolean extractingResWFiles, String resWOutputDirectory)
   at Microsoft.Build.Tasks.GenerateResource.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
### Expected  behavior
Builds project
### Actual behavior
Fails with multiple errors for all libraries
I was told on Gitter to tag @rainersigwald

**Comment by paul1956** [comment]
This is being addressed in #40012

**Comment by rainersigwald** [comment]
I'm very interested in the `GenerateResource` failure. Trying to build the `Core3.0` branch I didn't reproduce it. How did you get it?

**Comment by paul1956** [comment]
Upgraded to latest VS Preview compiled VB Core 3.0 class library's (project above) and all the Core 3.0 library (DLL) projects fail with the errors shown. Setting <MyType>Empty</MyType> in project file causes error to go away as does upgrading to Core daily of Microsoft .NET Cpre 3.0.100 - preview9.
