### ISSUE TITLE
Unhandled exception when worker node is connected to but the pipe is immediately closed

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4768]
We got an internal report of this exception in a VS uninstall scenario:

```
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode) in f:\dd\ndp\fx\src\Core\System\IO\Pipes\PipeStream.cs:line 1168
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state) in f:\dd\ndp\fx\src\Core\System\IO\Pipes\PipeStream.cs:line 560
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count) in f:\dd\ndp\fx\src\Core\System\IO\Pipes\PipeStream.cs:line 454
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count) in f:\dd\ndp\fx\src\Core\System\IO\Pipes\PipeStream.cs:line 440
   at Microsoft.Build.Internal.CommunicationsUtilities.WriteLongForHandshake(PipeStream stream, Int64 value) in /_/src/Shared/CommunicationsUtilities.cs:line 365
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc() in /_/src/Shared/NodeEndpointOutOfProcBase.cs:line 458
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state) in f:\dd\ndp\clr\src\BCL\system\threading\thread.cs:line 68
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 980
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 927
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 916
   at System.Threading.ThreadHelper.ThreadStart() in f:\dd\ndp\clr\src\BCL\system\threading\thread.cs:line 105
```

I believe what is happening is that something is starting an MSBuild worker node, connecting to it (sending the handshake to the worker), then immediately being terminated (before the worker can respond with its handshake).

This shouldn't crash; it should fail gracefully.

**Comment by rainersigwald** [comment]
@Forgind can you take a look at this?
