### ISSUE TITLE
ConditionalFact and VS 2019 results in "Catastrophic error during deserialization"

### ISSUE THREAD

**Issue by David-Engel** [microsoft/msbuild#4845]
### Steps to reproduce

Using ConditionalFact from Microsoft.xunit.netcore.extensions appears to be broken with VS 2019.

1. Extract the attached repro: [xUnitConditionalFact.zip](https://github.com/microsoft/msbuild/files/3769078/xUnitConditionalFact.zip)
2. Open xUnitConditionalFact.sln in VS 2019
3. Build the solution in Debug mode.
4. Open Test Explorer (menu: Test -> Test Explorer)
5. Run Test : ClassLibrary1.Class1.test
6. View the Output window and view Tests output

```
[10/24/2019 11:53:01.472 AM Informational] [xUnit.net 00:00:00.7506942]   Discovering: ClassLibrary1
[10/24/2019 11:53:01.581 AM Informational] [xUnit.net 00:00:00.8495606]   Discovered:  ClassLibrary1
[10/24/2019 11:53:01.589 AM Informational] ========== Discovery finished: 1 tests found (0:00:01.8119394) ==========
[10/24/2019 11:53:04.952 AM Informational] ---------- Discovery started ----------
[10/24/2019 11:53:04.957 AM Informational] ========== Discovery skipped: All test containers are up to date ==========
[10/24/2019 11:53:04.993 AM Informational] Executing test method: ClassLibrary1.Class1.test
[10/24/2019 11:53:05.008 AM Informational] ---------- Run started ----------
[10/24/2019 11:53:06.695 AM Warning] [xUnit.net 00:00:00.7855400] ClassLibrary1: Catastrophic error during deserialization: System.InvalidOperationException: Could not de-serialize type 'Xunit.NetCore.Extensions.SkippedTestCase' because it lacks a parameterless constructor.
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 213
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 40
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at Xunit.DefaultTestCaseBulkDeserializer.<BulkDeserialize>b__2_0(String serialization) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Descriptor\DefaultTestCaseBulkDeserializer.cs:line 22
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunit.DefaultTestCaseBulkDeserializer.BulkDeserialize(List`1 serializations) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Descriptor\DefaultTestCaseBulkDeserializer.cs:line 22
   at Xunit.Xunit2.BulkDeserialize(List`1 serializations) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 73
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[10/24/2019 11:53:06.728 AM Informational] [xUnit.net 00:00:00.8292123]   Starting:    ClassLibrary1
[10/24/2019 11:53:06.787 AM Informational] [xUnit.net 00:00:00.8881886]   Finished:    ClassLibrary1
[10/24/2019 11:53:06.966 AM Informational] ========== Run finished: 0 tests run (0:00:01.8771541) ==========
```

### Expected  behavior
When a parameter to a ConditionalFact returns false, the test should be marked as skipped.

### Actual behavior
When a parameter to a ConditionalFact returns false, it looks like test discovery fails with "Catastrophic error during deserialization" and tests are not evaluated.

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 16.3.1+1def00d3d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.3.1.50202
```
OS info:
Microsoft Windows [Version 10.0.17134.950]

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio Enterprise 2019 Version 16.3.3

**Comment by livarcocc** [comment]
@David-Engel I am sorry, I don't believe this is the appropriate repo for this issue. I would try either the xunit repo or microsoft/vstest.
