### ISSUE TITLE
Tests broken on xplat, CI server/script issue

### ISSUE THREAD

**Issue by radical** [Microsoft/msbuild#491]
The tests seem to be broken on xplat. The earlier failing log shows (http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/job/innerloop_xplat_Windows_NT/44/console)

```08:51:44      TwoSecondEmpty [FAIL]
08:51:44         System.ArgumentException : Xml_InvalidCommentChars
08:51:44         Stack Trace:
08:51:44            d:\j\workspace\innerloop_xpl---31ff7452\src\Shared\Compat\XmlTextWriter.cs(646,0): at System.Xml.XmlTextWriter.WriteComment(String text)
08:51:44               at System.Xml.XmlDocument.Save(XmlWriter w)
08:51:44            d:\j\workspace\innerloop_xpl---31ff7452\src\XMakeBuildEngine\Definition\Project.cs(1614,0): at Microsoft.Build.Evaluation.Project.SaveLogicalProject(TextWriter writer)
08:51:44            Evaluation\Preprocessor_Tests.cs(303,0): at Microsoft.Build.UnitTests.Preprocessor.Preprocessor_Tests.TwoSecondEmpty()```

These tests write current path inside an XML comment, but here the path is

`d:\j\workspace\innerloop_xpl---31ff7452\src...`

.. with the invalid `---` !

Older CI builds were using a different path `d:\j\workspace\Microsoft_msbuild\innerloop_xplat_Windows_NT\..` (http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/job/innerloop_xplat_Windows_NT/43/console)
with no invalid chars.

The tests should be fixed to handle this.

**Comment by radical** [comment]
Fixed now.

**Comment by radical** [comment]
Looks like this isn't the correct fix :/ The failure happens before we can do the string replace in the code. Investigating.

**Comment by radical** [comment]
The remaining issue was that the path was being written out as a comment while saving the project file.

**Comment by radical** [comment]
Fixed!
