### ISSUE TITLE
Cannot load project with ToolsVersion="15.0"

### ISSUE THREAD

**Issue by znakeeye** [microsoft/msbuild#4947]
Running Visual Studio 2019. Consider a C# project with `ToolsVersion` set to `15.0`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
  <!-- ... -->
</Project>
```

Then loading the project throws an error. Why?

```c#
ProjectCollection.GlobalProjectCollection.LoadProject(path);
```

```
Microsoft.Build.Exceptions.InvalidProjectFileException: Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "Current" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".  C:\Path\Foo.csproj.
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) in /_/src/Shared/ProjectErrorUtilities.cs:line 412
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider, IFileSystem fileSystem) in /_/src/Build/Definition/Project.cs:line 3245
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean profileEvaluation, Boolean interactive) in /_/src/Build/Evaluation/Evaluator.cs:line 212
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive) in /_/src/Build/Evaluation/Evaluator.cs:line 295
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2713
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2688
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2797
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 516
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion) in /_/src/Build/Definition/ProjectCollection.cs:line 1150
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName) in /_/src/Build/Definition/ProjectCollection.cs:line 1070
   at ...
```

**Comment by znakeeye** [comment]
Solved it by installing `Microsoft.Build.Runtime`:

```
Install-Package Microsoft.Build.Runtime -Version 16.3.0
```

**Comment by rainersigwald** [comment]
@znakeeye also see https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2019 -- it depends on your scenario, but you probably want to use MSBuildLocator in order to be able to load projects "like Visual Studio".

**Comment by znakeeye** [comment]
It seems very hard to get this `Locator` to work in a unit test project. It keeps telling me this:

> System.InvalidOperationException: Microsoft.Build.Locator.MSBuildLocator.RegisterInstance was called, but MSBuild assemblies were already loaded.
>     Ensure that RegisterInstance is called before any method that directly references types in the Microsoft.Build namespace has been called.
>     Loaded MSBuild assemblies: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>     Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
>   Stack Trace: 

So I tried skipping the registration part, but then I get the original error as described above.

**Comment by rainersigwald** [comment]
@znakeeye You must call Locator before entering any method that uses the MSBuild API. In unit test projects, that's often in a test-setup method (usually at the class or assembly level).

**Comment by morrisond91** [comment]
I have an exe that generates some c# classes and i am using var project = new Microsoft.Build.Evaluation.Project(projectFile); this code to add items on the fly

i've installed these

```
<package id="Microsoft.Build" version="16.4.0" targetFramework="net472" />
  <package id="Microsoft.Build.Framework" version="16.4.0" targetFramework="net472" />
  <package id="Microsoft.Build.Runtime" version="16.4.0" targetFramework="net472" />
  <package id="Microsoft.Build.Tasks.Core" version="16.4.0" targetFramework="net472" />
  <package id="Microsoft.Build.Utilities.Core" version="16.4.0" targetFramework="net472" />
```

and getting this error
Microsoft.Build.Exceptions.InvalidProjectFileException: 'The tools version "Current" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  D:\JoinersAgent2\_work\43\s\project.csproj

i can't figure it out.
``

**Comment by qub1n** [comment]
@morrisond91 How did you resolved it?

**Comment by icnocop** [comment]
I was able to solve this issue by installing the nuget package `Microsoft.Build.Runtime` as indicated and/or setting the `MSBUILD_EXE_PATH` environment variable as indicated [here](https://github.com/dotnet/roslyn/issues/44746#issue-628419626).

`Environment.SetEnvironmentVariable("MSBUILD_EXE_PATH", @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe");`

**Comment by notes2c** [comment]
> I have an exe that generates some c# classes and i am using
> 
> `var project = new Microsoft.Build.Evaluation.Project(projectFile); `
> 
> this code to add items on the fly
> 
> ```
> foreach (var controller in workList)
> {
>       project.AddItem("Compile", $@"{targetFolder}\{controller}");
>  }
> ```
> 
> i've installed these
> 
> ```
> <package id="Microsoft.Build" version="16.4.0" targetFramework="net472" />
> <package id="Microsoft.Build.Framework" version="16.4.0" targetFramework="net472" />
> <package id="Microsoft.Build.Runtime" version="16.4.0" targetFramework="net472" />
> <package id="Microsoft.Build.Tasks.Core" version="16.4.0" targetFramework="net472" />
> <package id="Microsoft.Build.Utilities.Core" version="16.4.0" targetFramework="net472" />
> ```
> 
> and getting this error
> 
> ```
> Microsoft.Build.Exceptions.InvalidProjectFileException: 'The tools version "Current" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  D:\JoinersAgent2\_work\43\s\project.csproj
> ```
> 
> i can't figure it out.

We see the same problem now after latest update of Visual Studio 2022 from 17.7.3 -> 17.7.4
And I am also very interested in a solution that can fix this issue.
The error make no sense and we have not made any changes to the source code, only the Visual Studio update.
