### ISSUE TITLE
Unhandled exception. System.Resources.MissingManifestResourceException:

### ISSUE THREAD

**Issue by w4mmp** [microsoft/msbuild#5104]
Hello,
I was directed to start an issue in msbuild by https://github.com/davkean  (issue: project-system #2100).

This may be an issue with my port from a Windows Forms application to dotnet 3.1 but I am at a lost as to how to correct it.
Regards,
Ron
[mscc.zip](https://github.com/microsoft/msbuild/files/4151196/mscc.zip)

### Steps to reproduce
1) Build the included project.
2) Run - dotnet mscc.dll

Output of dotnet:
G:\Ham Radio\ominaSDR\Hardware\Linux\dotnettest\mscc\Release\netcoreapp3.1>dotnet mscc.dll
Unhandled exception. System.Resources.MissingManifestResourceException: Could not find the resource "OmniaGUI.Main_form.resources" among the resources "mscc.Properties.Resources.resources" embedded in the assembly "mscc", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.Resources.ResourceManager.GetString(String name)
   at OmniaGUI.Main_form.InitializeComponent() in G:\Ham Radio\ominaSDR\Hardware\Linux\dotnettest\mscc\Main_Form.designer.cs:line 1403
   at OmniaGUI.Main_form..ctor() in G:\Ham Radio\ominaSDR\Hardware\Linux\dotnettest\mscc\Main_Form.cs:line 105
   at OmniaGUI.Program.Main() in G:\Ham Radio\ominaSDR\Hardware\Linux\dotnettest\mscc\Program.cs:line 20

OS info:
Windows 10

Microsoft Visual Studio Community 2019
Version 16.4.4
VisualStudio.16.Release/16.4.4+29728.190
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA205
Microsoft Visual C++ 2019

.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.

ASP.NET and Web Tools 2019   16.4.460.23317
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.4.460.23317
Azure App Service Tools v3.0.0

C# Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

NuGetReferenceSwitcher   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

UpgradeCommand Extension   1.0
UpgradeCommand Visual Studio Extension Detailed Info

Visual Basic Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by w4mmp** [comment]
Folks,
Any update on this?  I could really use a hand with this.   If this is the wrong area for this issue, just let me know.
