### ISSUE TITLE
Unlogged error in RAR (?)

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#5150]
@sharwell reported offline an IDE build that suddenly failed without any error messages. He was able to capture an exception using PerfView

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.Build.Shared.AssemblyNameExtension.GetAssemblyNameEx(String path)
   at Microsoft.Build.Tasks.SystemState.GetAssemblyName(String path)
   at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName)
   at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryItems(ITaskItem[] referenceAssemblyFiles, ITaskItem[] referenceAssemblyNames, List`1 exceptions)
   at Microsoft.Build.Tasks.ReferenceTable.ComputeClosure(IEnumerable`1 remappedAssembliesValue, ITaskItem[] referenceAssemblyFiles, ITaskItem[] referenceAssemblyNames, List`1 exceptions)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<InitializeAndExecuteTask>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteBucket>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__49.MoveNext()
```

**Comment by rainersigwald** [comment]
@Forgind can you try injecting an exception at that callsite and seeing if we really do swallow it without logging a useful error?

**Comment by Forgind** [comment]
I inserted the OutOfMemoryException in AssemblyNameExtension.cs, and when I forced it to execute it, I got this:
```C:\Users\forgind\Documents\GitHub\msbuild>artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\MSBuild.exe MSBuild.Dev.sln /m:1
Microsoft (R) Build Engine version 16.6.0-dev-20128-01+13cfe7fc5 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.Build.Framework -> C:\Users\forgind\Documents\GitHub\msbuild\artifacts\bin\Microsoft.Build.Framework\Debug
  \netstandard2.0\Microsoft.Build.Framework.dll
  Microsoft.Build -> C:\Users\forgind\Documents\GitHub\msbuild\artifacts\bin\Microsoft.Build\Debug\netcoreapp2.1\Micro
  soft.Build.dll
  Microsoft.Build.Framework -> C:\Users\forgind\Documents\GitHub\msbuild\artifacts\bin\Microsoft.Build.Framework\Debug
  \net472\Microsoft.Build.Framework.dll
  Xunit.NetCore.Extensions -> C:\Users\forgind\Documents\GitHub\msbuild\artifacts\bin\Xunit.NetCore.Extensions\Debug\n
  etstandard2.0\Xunit.NetCore.Extensions.dll
  PortableTask -> C:\Users\forgind\Documents\GitHub\msbuild\artifacts\bin\Samples\PortableTask\Debug\netstandard1.3\Po
  rtableTask.dll

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:29.32
```

Looks like a real problem to me.

**Comment by Forgind** [comment]
I did, however, get this to pop up:
![image](https://user-images.githubusercontent.com/12969783/75571515-372d9e80-5a0e-11ea-9efb-f43d80cab4d8.png)
It's possible that only came up because I was building from the command line. Either way, there's a problem here.

**Comment by rainersigwald** [comment]
@Forgind I think those dialogs pop up for debug builds but not release--might be worth trying with the `Release` config to see if it goes away.

Sounds like the next steps here are to catch the initial exception in a debugger and step forward to see what's catching it.

**Comment by Forgind** [comment]
This seems to only happen when an exception is classified as a critical exception, as OutOfMemoryExceptions are. Such exceptions are swallowed twice: once [here](https://github.com/microsoft/msbuild/blob/master/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L701) (note that [`ErrorUtilities.ThrowInternalError`](https://github.com/microsoft/msbuild/blob/master/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L710) prevents execution, so the throw isn't hit) and once [here](https://github.com/microsoft/msbuild/blob/master/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L621).

I'm going to unassign myself for now until this starts becoming a major issue.

**Comment by sharwell** [comment]
@Forgind I hit this 5 more times this morning

**Comment by sharwell** [comment]
@Forgind Apparently this is just my life now 😢

**Comment by sharwell** [comment]
@Forgind I hit this 2 times so far today.

**Comment by sharwell** [comment]
What if we just remove this block? Wouldn't the `finally` section ensure the exception gets logged?

https://github.com/microsoft/msbuild/blob/ba9a1d64a7abf15a8505827c00413156a3eb7f62/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L754-L761

**Comment by Forgind** [comment]
> What if we just remove this block? Wouldn't the `finally` section ensure the exception gets logged?
> 
> https://github.com/microsoft/msbuild/blob/ba9a1d64a7abf15a8505827c00413156a3eb7f62/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L754-L761

The finally section runs either way, and without this block, a critical exception can't percolate to the top layer and display the full stack. The OOM exception is caught either way, as it is now, but that would additionally block other exceptions.

**Comment by sharwell** [comment]
I'm hitting this again this morning ☹️
