### ISSUE TITLE
Multi-proc build fails with ArgumentException if the CreateItem task is used

### ISSUE THREAD

**Issue by ladipro** [microsoft/msbuild#5225]
### Steps to reproduce

1.proj
```xml
<Project DefaultTargets="Build">
    <Target Name="Build">
        <MSBuild Projects="2.proj" Targets="Build" />
    </Target>
</Project>
```
2.proj
```xml
<Project DefaultTargets="Build">
    <Target Name='Build' Returns="@(x)">
        <CreateItem Include='$(programfiles)\reference assemblies\**\*.dll;'>
            <Output TaskParameter='Include' ItemName='x' />
        </CreateItem>
    </Target>
</Project>
```

build with
```
set MSBUILDNOINPROCNODE=1
set MSBUILDTARGETRESULTCOMPRESSIONTHRESHOLD=0

msbuild.exe 1.proj /clp:ShowCommandLine /m:1 /verbosity:n /nr:false /bl /fl /flp:v=diagnostic
```
### Expected behavior
Build succeeds.

### Actual behavior
```
error MSB4018: The "MSBuild" task failed unexpectedly.
error MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
error MSB4018: System.ArgumentException: The "RecursiveDir" name is reserved, and cannot be used.
error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args) in C:\src\msbuild\src\Shared\ErrorUtilities.cs:line 482
error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(Boolean condition, Exception innerException, String resourceName, Object arg0) in C:\src\msbuild\src\Shared\ErrorUtilities.cs:line 614
error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(Boolean condition, String resourceName, Object arg0) in C:\src\msbuild\src\Shared\ErrorUtilities.cs:line 515
error MSB4018:    at Microsoft.Build.Execution.ProjectMetadataInstance..ctor(String name, String escapedValue, Boolean allowItemSpecModifiers) in C:\src\msbuild\src\Build\Instance\ProjectMetadataInstance.cs:line 72
error MSB4018:    at Microsoft.Build.Execution.ProjectMetadataInstance..ctor(String name, String escapedValue) in C:\src\msbuild\src\Build\Instance\ProjectMetadataInstance.cs:line 45
error MSB4018:    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.TranslateWithInterning(ITranslator translator, LookasideStringInterner interner) in C:\src\msbuild\src\Build\Instance\ProjectItemInstance.cs:line 1620
error MSB4018:    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem..ctor(ITranslator translator, LookasideStringInterner interner) in C:\src\msbuild\src\Build\Instance\ProjectItemInstance.cs:line 859
error MSB4018:    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.FactoryForDeserialization(ITranslator translator, LookasideStringInterner interner) in C:\src\msbuild\src\Build\Instance\ProjectItemInstance.cs:line 1581
error MSB4018:    at Microsoft.Build.Execution.TargetResult.ItemsStore.DecompressItems() in C:\src\msbuild\src\Build\BackEnd\Shared\TargetResult.cs:line 511
error MSB4018:    at Microsoft.Build.Execution.TargetResult.ItemsStore.get_Items() in C:\src\msbuild\src\Build\BackEnd\Shared\TargetResult.cs:line 426
error MSB4018:    at Microsoft.Build.Execution.TargetResult.get_Items() in C:\src\msbuild\src\Build\BackEnd\Shared\TargetResult.cs:line 96
error MSB4018:    at Microsoft.Build.BackEnd.TaskHost.<BuildProjectFilesInParallelAsync>d__58.MoveNext() in C:\src\msbuild\src\Build\BackEnd\Components\RequestBuilder\TaskHost.cs:line 942
```

### Environment data
`msbuild /version` output:

```
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.5.0.12403
```

as well as current master (9f3e4e72).

**Comment by ladipro** [comment]
Caused by the CreateItem task setting the `RecursiveDir` metadata on items, and this built-in item-spec modifier being rejected during deserialization.

Reproduces only if the amount of items returned from a target meets the compression threshold, as implemented in `TargetResult`. No such validation of metadata names takes place if compression is not used.
