### ISSUE TITLE
MSB4017 InternalLoggerException System.ArgumentNullException: Parameter "projectProperty" cannot be null.

### ISSUE THREAD

**Issue by danmosemsft** [microsoft/msbuild#5267]
Porting https://github.com/dotnet/runtime/issues/34820
```
2020-04-10T13:54:36.4464394Z Time Elapsed 00:02:01.94
2020-04-10T13:54:36.4702588Z MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
2020-04-10T13:54:36.4708316Z Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.
2020-04-10T13:54:36.4709785Z  ---> System.ArgumentNullException: Parameter "projectProperty" cannot be null.
2020-04-10T13:54:36.4710517Z    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull(Object parameter, String parameterName, String resourceName)
2020-04-10T13:54:36.4711180Z    at Microsoft.Build.Collections.CopyOnWritePropertyDictionary`1.Set(T projectProperty)
2020-04-10T13:54:36.4711735Z    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.get_MetadataCollection()
2020-04-10T13:54:36.4712263Z    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CloneCustomMetadata()
2020-04-10T13:54:36.4712784Z    at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)
2020-04-10T13:54:36.4713290Z    at Microsoft.Build.Logging.BuildEventArgsWriter.WriteItems(IEnumerable items)
2020-04-10T13:54:36.4713915Z    at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)
2020-04-10T13:54:36.4714445Z    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
2020-04-10T13:54:36.4715224Z    --- End of inner exception stack trace ---
2020-04-10T13:54:36.4716248Z    at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
2020-04-10T13:54:36.4717058Z    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
2020-04-10T13:54:36.4717714Z    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
2020-04-10T13:54:36.5134290Z ##[error](NETCORE_ENGINEERING_TELEMETRY=Build) Build failed (exit code '1').
```
this occurred with `/__w/1/s/.dotnet/sdk/5.0.100-preview.4.20202.8/MSBuild.dll` on Android.

This would presumably include the change made to temporarily patch https://github.com/microsoft/msbuild/issues/4322

It seems there is some concurrent read/write going on in the dictionary here. It's obviously a copy-on-write dictionary -- should the "write" have been forced, before the logging thread gets hold of it @rainersigwald ?

**Comment by danmosemsft** [comment]
@KirillOsenkov  in case this is relevant to the binary logger

**Comment by KirillOsenkov** [comment]
I pulled the binlog from the Libraries Android x86 Debug build and the MSBuild version is: `MSBuild version = "16.6.0-preview-20173-01+2d82e1a86"`

This version does contain @ViktorHofer fix from https://github.com/microsoft/msbuild/pull/4355/files, however the fix is ineffective because it doesn't surround this call to CloneCustomMetadata:
https://github.com/microsoft/msbuild/blob/2f58c1427384aaf012d616ae12849e7d9b5c0f10/src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs#L600

**Comment by KirillOsenkov** [comment]
Note that the stack in https://github.com/microsoft/msbuild/issues/4322 is different:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Build.Collections.CopyOnWritePropertyDictionary`1.get_Item(String name)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadataEscaped(String metadataName)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadata(String metadataName)
   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)
```

whereas the stack here is:
```
System.ArgumentNullException: Parameter "projectProperty" cannot be null.
Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull(Object parameter, String parameterName, String resourceName)
Microsoft.Build.Collections.CopyOnWritePropertyDictionary`1.Set(T projectProperty)
Microsoft.Build.Execution.ProjectItemInstance.TaskItem.get_MetadataCollection()
Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CloneCustomMetadata()
Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)
```

I think our stack can actually happen when `metadatum` being passed to `Set()` here is null:
https://github.com/microsoft/msbuild/blob/2f58c1427384aaf012d616ae12849e7d9b5c0f10/src/Build/Instance/ProjectItemInstance.cs#L1081

**Comment by KirillOsenkov** [comment]
For this case I suggest https://github.com/microsoft/msbuild/pull/5271 as a temporary measure. My understanding is that it's very intermittent, so this plugs the leak and buys us more time to investigate.

Or likely just kill CopyOnWriteDictionary with prejudice as we've been apparently planning for a while now ;)

The real question is how is that metadatum ever null? Should we perhaps add more checks upstream to prevent null from ever being there?

**Comment by KirillOsenkov** [comment]
From inspecting both places I don't see how an element in metadata could be null, other than a race condition (CopyOnWriteDictionary being written to or resized while it's being read).

Overall COWDictionary is not memory efficient, not threadsafe and looks clumsy. I'm pretty sure this is one of those cases where when we replace it with immutable collections the bug will disappear and we'll never really know what the problem was.

**Comment by danmosemsft** [comment]
> CopyOnWriteDictionary being written to or resized while it's being read

I’m guessing that’s what’s happening. Is this collection expected to be written concurrently? If it is not then changing to a concurrent collection seems like masking the real issue (on top of adding that catch). ConcurrentDictionary is not small or cheap necessarily.

**Comment by KirillOsenkov** [comment]
We were thinking Immutable, not Concurrent. This would enable atomic updates and lock-free thread safety.

**Comment by danmosemsft** [comment]
Ah - I misread 🙂

**Comment by rainersigwald** [comment]
Yeah, switching to Immutable is a) a direct conceptual replacement, b) a better-designed implementation memory and safety-wise, and c) nontrivial because these things sometimes cross AppDomains and thus need to be binaryformatter serializable. I got stuck on the latter the last time I took a crack at it but I think I know how to do it now and may give it a try again shortly.
