### ISSUE TITLE
System.Runtime.InteropServices.COMException during build

### ISSUE THREAD

**Issue by kunalspathak** [microsoft/msbuild#5442]
### Steps to reproduce

Either include a project sample, attach a zipped project, or provide IDE / CLI steps to create the project and repro the behaviour. Example of a project sample:

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp5.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>
<PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>

```

Directory contents:
```
/
- helloworld.cs
```

Command line
```
dotnet build -c Release
```
### Expected behavior
Pass

### Actual behavior
```
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 11460:
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166: =====================
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166: 6/17/2020 10:06:51 AM
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166: System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (0x80004005 (E_FAIL))
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at System.Runtime.InteropServices.GCHandle.InternalSet(IntPtr handle, Object value)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at System.Runtime.InteropServices.GCHandle.set_Target(Object value)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.WeakStringCache.GetOrCreateEntry[T](T internable, Boolean& cacheHit)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.OpportunisticIntern.WeakStringCacheInterner.TryIntern[T](T candidate, String& interned)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.OpportunisticIntern.WeakStringCacheInterner.InterningToString[T](T candidate)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.OpportunisticIntern.InternableToStringImpl[T](T candidate)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.InterningBinaryReader.ReadString()
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BinaryTranslator.BinaryReadTranslator.TranslateCulture(CultureInfo& value)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters..ctor(ITranslator translator)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters.FactoryForDeserialization(ITranslator translator)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.TranslatorHelpers.Translate[T](ITranslator translator, T& instance, NodePacketValueFactory`1 valueFactory)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeConfiguration.Translate(ITranslator translator)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeConfiguration.FactoryForDeserialization(ITranslator translator)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodePacketFactory.PacketFactoryRecord.DeserializeAndRoutePacket(Int32 nodeId, ITranslator translator)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, ITranslator translator)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.Execution.OutOfProcNode.Microsoft.Build.BackEnd.INodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, ITranslator translator)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166: ===================
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:
[2020/06/17 10:06:51][INFO] MSBUILD : error MSB4166:
```

### Environment data
`msbuild /version` output:

```cmd
> dotnet build /version

Microsoft (R) Build Engine version 16.7.0-preview-20310-07+ee1c9fd0c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

16.7.0.31007

> dotnet --info

.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20317.1
 Commit:    792ade3e93

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   c:\git\performance\tools\dotnet\arm64\sdk\5.0.100-preview.7.20317.1\

Host (useful for support):
  Version: 5.0.0-preview.7.20315.3
  Commit:  279940471d

.NET SDKs installed:
  5.0.100-preview.3.20169.11 [c:\git\performance\tools\dotnet\arm64\sdk]
  5.0.100-preview.6.20270.13 [c:\git\performance\tools\dotnet\arm64\sdk]
  5.0.100-preview.7.20317.1 [c:\git\performance\tools\dotnet\arm64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.3.20169.4 [c:\git\performance\tools\dotnet\arm64\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20269.9 [c:\git\performance\tools\dotnet\arm64\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20311.11 [c:\git\performance\tools\dotnet\arm64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20169.1 [c:\git\performance\tools\dotnet\arm64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20264.1 [c:\git\performance\tools\dotnet\arm64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20315.3 [c:\git\performance\tools\dotnet\arm64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20270.2 [c:\git\performance\tools\dotnet\arm64\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20311.4 [c:\git\performance\tools\dotnet\arm64\shared\Microsoft.WindowsDesktop.App]
```

OS info: Windows ARM64

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by Forgind** [comment]
Is this related to #5353, @ladipro?

**Comment by ladipro** [comment]
Yes, definitely related and appears to be specific to ARM64. @kunalspathak, does it reproduce consistently or does it look like a race? Would it be possible to let me access the repro host or share a dump of the crashing process at the point where it throws the exception?

**Comment by kunalspathak** [comment]
> Yes, definitely related and appears to be specific to ARM64. @kunalspathak, does it reproduce consistently or does it look like a race? Would it be possible to let me access the repro host or share a dump of the crashing process at the point where it throws the exception?

Appears to be a race condition. It repros in every other run. I will send you the dump over the email.

**Comment by ladipro** [comment]
@kunalspathak thank you. I think it's safe to say that the issue was introduced with https://github.com/microsoft/msbuild/pull/5353

I am waiting for an ARM64 machine to live debug this and verify a fix. In the meantime please use the following environment variable to work around it:

```
SET MSBuildUseLegacyStringInterner=1
```

**Comment by ladipro** [comment]
@kunalspathak I haven't been able to reproduce but the code definitely had a bug that was very likely the root cause of this issue. Please give it another try when the fix reaches your environment. Thanks a lot for reporting this!
