### ISSUE TITLE
Incorrectly escaped path when building regex in ReadAllToolsets

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#695]
```
11:59:04 
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
11:59:04 System.ArgumentException: parsing 'D:\j\workspace\_Windows_NT_p---ab87db35\bin\xbuild\\d+\.\d+' - Unrecognized escape sequence \\j.
11:59:04    at System.Text.RegularExpressions.RegexParser.ScanCharEscape()
11:59:04    at System.Text.RegularExpressions.RegexParser.ScanBasicBackslash()
11:59:04    at System.Text.RegularExpressions.RegexParser.ScanRegex()
11:59:04    at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
11:59:04    at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
11:59:04    at System.Text.RegularExpressions.Regex..ctor(String pattern)
11:59:04    at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
11:59:04    at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection()
11:59:04    at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
11:59:04    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
11:59:04    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
```

See http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/job/_Windows_NT_prtest/480/consoleFull#77265618979494335-f7bd-47d0-8771-8661e00c2db2

The path part should be escaped before feeding it to the regex ctor.

**Comment by rainersigwald** [comment]
The fix from @mfilippov was merged into xplat long ago. Thanks!
