### ISSUE TITLE
MSBuild is trying to PInvoke to Kernel32 on Linux

### ISSUE THREAD

**Issue by moozzyk** [Microsoft/msbuild#757]
I have this in my target:
```
 <Exec Command="python" />
```
Since I did not pass any parameters it started REPL and blocked the build. So I pressed Ctrl+C and MSBuild failed trying to PInvoke into Kernel32.dll

```
Build started 7/1/16 11:39:17 PM.
The target "Initialize" listed in a BeforeTargets attribute at "/home/moozzyk/source/libuv-build/.build/KoreBuild/src/Microsoft.AspNetCore.Build/targets/Initialize.targets (97,79)" does not exist in the project, and will be ignored.
Project "/home/moozzyk/source/libuv-build/makefile.proj" on node 1 (default targets).
BuildLinux:
  Linux, Platform: Linux
  python
  Python 2.7.6 (default, Jun 22 2015, 17:58:13)
  [GCC 4.8.2] on linux2
  Type "help", "copyright", "credits" or "license" for more information.
^C  >>>
  KeyboardInterrupt
Attempting to cancel the build...
/home/moozzyk/source/libuv-build/makefile.proj(16,5): warning MSB5021: "sh" and its child processes are being terminated in order to cancel the build.
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018: The "Exec" task failed unexpectedly.
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018: System.DllNotFoundException: Unable to load DLL 'KERNEL32.DLL': The specified module could not be found.
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:  (Exception from HRESULT: 0x8007007E)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.OpenProcess(eDesiredAccess dwDesiredAccess, Boolean bInheritHandle, Int32 dwProcessId)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.KillTree(Int32 processIdToKill)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.KillToolProcessOnTimeout(Process proc, Boolean isBeingCancelled)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Tasks.Exec.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
Done Building Project "/home/moozzyk/source/libuv-build/makefile.proj" (default targets) -- FAILED.
```

**Comment by rainersigwald** [comment]
Thanks for the report! We're tracking this as #434, so I'm going to close this as a duplicate.
