### ISSUE TITLE
UnGACed MSBuild can fail type checks when a task loads MSBuild assemblies from the amd64 folder

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#834]
The same type, when loaded in a new appdomain in an amd64 MSBuild process, will be loaded from the copy of the DLL in the amd64 subfolder, not the one from bin. This means that checks for type equality will fail, because the types being compared may be from different physical assemblies on disk (even if they're bitwise identical).

This is new to the Willow experience, because MSBuild was always in the GAC before--so any attempt to load an MSBuild assembly would load it from the GAC, rather than the path that was requested. That ensured that there was no mismatch.

One possible symptoms of this:

```
The "GenerateResource" task failed unexpectedly.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Somehow got a wrong and possibly incompatible type for ProcessResourceFiles.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.Tasks.GenerateResource.Execute()
   at Microsoft.Build.CommandLine.OutOfProcTaskAppDomainWrapperBase.InstantiateAndExecuteTask(IBuildEngine oopTaskHostNode, LoadedType taskType, String taskName, String taskLocation, String taskFile, Int32 taskLine, Int32 taskColumn, AppDomainSetup appDomainSetup, IDictionary`2 taskParams)
```

**Comment by rainersigwald** [comment]
Long fixed.
