### ISSUE TITLE
Clone + build.cmd fails two tests on my machine

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#939]
These tests fail for me in desktop runs of the master branch:
- Microsoft.Build.UnitTests.ToolLocationHelper_Tests.GetPathToDotNetFrameworkSdk
- Microsoft.Build.UnitTests.ToolLocationHelper_Tests.VerifyToolsetAndToolLocationHelperAgree

```
      Expected: D:\Src\msbuild\bin\x86\Windows_NT\Debug
      Actual:   C:\Program Files (x86)\Microsoft SDKs\Winúúú
                 (pos 0)
      Stack Trace:
        ToolLocationHelper_Tests.cs(843,0): at Microsoft.Build.UnitTests.ToolLocationHelper_Tests.GetPathToDotNetFrameworkSdk()

      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        ToolLocationHelper_Tests.cs(1010,0): at Microsoft.Build.UnitTests.ToolLocationHelper_Tests.VerifyToolsetAndToolLocationHelperAgree()

=== TEST EXECUTION SUMMARY ===
   Microsoft.Build.Utilities.UnitTests  Total: 414, Errors: 0, Failed: 2, Skipped: 64, Time: 22.346s
```

@rainersigwald

**Comment by rainersigwald** [comment]
Closing as a duplicate of #995 which has a couple other failures listed.
