### ISSUE TITLE
MSBuild fails to initialize when used as an API

### ISSUE THREAD

**Issue by DustinCampbell** [Microsoft/msbuild#999]
OS: Windows x64

I'm working on integrating the latest MSBuild bits from MyGet (0.1.0-preview-00033-160829) into OmniSharp. However, it throws when OmniSharp attempts to instantiate a ProjectCollection.

```
System.TypeInitializationException: The type initializer for 'BuildEnvironmentHelperSingleton' threw an exception. ---> System.InvalidOperationException: Could not determine a valid location to MSBuild. Try running this process from the Developer Command Prompt for Visual Studio.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Shared.BuildEnvironmentHelper.Initialize()
   at Microsoft.Build.Shared.BuildEnvironmentHelper.BuildEnvironmentHelperSingleton..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection()
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String projectFilePath, String solutionDirectory, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics) in C:\Projects\omnisharp-roslyn\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 118
   at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProjectFileInfo(String projectFilePath) in C:\Projects\omnisharp-roslyn\src\OmniSharp.MSBuild\MSBuildProjectSystem.cs:line 205
```

From the [MSBuild code](https://github.com/Microsoft/msbuild/blob/60c73c914c01c62f5496c6d04683f77e967bbc68/src/Shared/BuildEnvironmentHelper.cs#L39-L92) that's failing, it looks it's trying very hard to find the location that MSBuild is installed on the machine. However, this is a scenario where MSBuild is being hosted in a different app, so I'm not sure why this would be needed.

**Comment by DustinCampbell** [comment]
I should mention that this appears to be a regression from 0.1.0-preview-00028-160627, which seems to work fine.

**Comment by DustinCampbell** [comment]
Also, OmniSharp is a standalone .NET Core app which uses MSBuild to perform a DesignTimeBuild in order to drive the editing experience for VS Code (and other editors).

**Comment by natemcmaster** [comment]
I've encountered the same issue. For now, my workaround has been to set the environment variable "MSBUILD_EXE_PATH" to the full path of msbuild.exe. Unfortunately, this requires knowing where to find it...which is another problem altogether

**Comment by DustinCampbell** [comment]
That unfortunately assumes that MSBuild is on the system. OmniSharp needs to operate even when MSBuild is not installed elsewhere.

**Comment by DustinCampbell** [comment]
@AndyGerlicher, @rainersigwald, @Craig-Campbell-MS: Has anyone looked at this issue yet? It's blocking further work on getting the latest MSBuild bits working for VS Code.

**Comment by DustinCampbell** [comment]
Also adding @Sarabeth-Jaffe-Microsoft

**Comment by DustinCampbell** [comment]
Thanks for starting a chat over email @AndyGerlicher. It turns out that the problem is that I needed to reference 1 additional package. :smile:. I was referencing the following packages:

```
"Microsoft.Build": "0.1.0-preview-00033-160829",
"Microsoft.Build.Framework": "0.1.0-preview-00033-160829",
"Microsoft.Build.Targets": "0.1.0-preview-00033-160829",
"Microsoft.Build.Tasks.Core": "0.1.0-preview-00033-160829",
"Microsoft.Build.Utilities.Core": "0.1.0-preview-00033-160829",
```

However, I also needed to reference:

```
"MSBuild": "0.1.0-preview-00033-160829",
```

That delivers msbuild.exe and gets past the type initializer issue.
